export default class LocalPathActions {
  static POLL_LOCALPATH = 'POLL_LOCALPATH';
  static REQUEST_LOCALPATH_SUCCESS = 'REQUEST_LOCALPATH_SUCCESS';
  static REQUEST_LOCALPATH_FAILURE = 'REQUEST_LOCALPATH_FAILURE';
}
