@startuml

hide footbox

actor Human
participant ROS
participant node_navigate
participant Sailbot
participant node_navigate_observer
participant MultiprocessManager
participant SailbotObserver
participant VisualizerState
participant visualizer.py
participant Dash


Human -> ROS : ros2 launch
ROS -> node_navigate: main()
node_navigate -> Sailbot: launch node
ROS -> node_navigate_observer: main()
node_navigate_observer -> MultiprocessManager: create shared queue
MultiprocessManager -> node_navigate_observer: queue
node_navigate_observer -> SailbotObserver: fork and launch node with queue
node_navigate_observer -> visualizer.py: fork and call dash_app() with queue
visualizer.py -> Dash: run()
Dash -->> : starts web app

group concurrent processes
    loop
        Sailbot -> Sailbot: publish LPathData msg
        SailbotObserver -> SailbotObserver: append LPathData msg to self.msgs
        SailbotObserver -> VisualizerState: create state from msgs
        VisualizerState -> SailbotObserver: state
        SailbotObserver -> SailbotObserver: queue.put(state)
    end

    loop
        Dash -> visualizer.py++ : live_plot()
        visualizer.py -> visualizer.py: get next state from queue
        visualizer.py -> visualizer.py++: live_update_plot
        visualizer.py -> visualizer.py++: initial plot
        note right of visualizer.py
            creates a brand new empty plot
        end note
        return fig
        visualizer.py -> visualizer.py: add all traces to plot
        return fig
        return fig
        Dash -> : redraw plot
    end
end

@enduml
