export default class GraphsActions {
    static REARRANGE_GRAPHS = 'REARRANGE_GRAPHS';
    static REARRANGE_GRAPHS_SUCCESS = 'REARRANGE_GRAPHS_SUCCESS';
    static REARRANGE_GRAPHS_FAILURE = 'REARRANGE_GRAPHS_FAILURE';
  }
