# Template for the remote_transceiver module
remote_transceiver_node:
  ros__parameters:
    enabled: true
    # The following parameters are optional. Defaults are set in remote_transceiver_ros_intf.cpp
    db_name: # String: Name of mongodb database
    host: # String: IP or URL that the Remote Transceiver will use for the server (ex. 127.0.0.1)
    port: # Integer: Port that the Remote Transceiver will use for the server (ex. 8081)
    num_threads: # Integer: Number of concurrent threads available to accept simulataneous HTTP requests
