changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:

    - title: "Bug Fixes :beetle:"
      labels:
        - bug

    - title: "Dev Container Configuration Changes :whale:"
      labels:
        - devcontainer

    - title: "VS Code Configuration Changes :computer:"
      labels:
        - vscode

    - title: "GitHub Configuration Changes :octocat:"
      labels:
        - github

    - title: "Other Changes :hammer_and_wrench:"
      labels:
        - "*"
