changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Infrastructure Updates
      labels:
        - infrastructure
    - title: Other Changes
      labels:
        - "*"
