changelog:
  exclude:
    labels:
      - ignore-for-release

    authors:
      - dependabot
      - imgbot

  # emoji reference (outdated): https://gist.github.com/rxaviers/7360908
  categories:
    - title: "Bug Fixes :beetle:"
      labels:
        - bug

    - title: "Website Changes :computer:"
      labels:
        - web

    - title: "Pathfinding Changes :earth_americas:"
      labels:
        - path

    - title: "Boat Simulator Changes :video_game:"
      labels:
        - sim

    - title: "Controller Changes :boat:"
      labels:
        - ctrl

    - title: "Network Systems Changes :artificial_satellite:"
      labels:
        - net

    - title: "Docs Site Changes :book:"
      labels:
        - docs

    - title: "Infrastructure Changes :hammer_and_wrench:"
      labels:
        - infrastructure

    - title: "Other Changes"
      labels:
        - "*"
