changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Devcontainer Updates
      labels:
        - devcontainer
    - title: Workflow Updates
      labels:
        - workflows
    - title: General Infrastructure Updates
      labels:
        - infrastructure
    - title: Other Changes
      labels:
        - "*"
