changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:

    - title: "Bug Fixes :beetle:"
      labels:
        - bug
    
    - title: "Docker Changes :whale:"
      labels:
        - devcontainer

    - title: "VS Code Configuration Changes :computer:"
      labels:
        - vscode

    - title: "Workflow Changes :octocat:"
      labels:
        - workflows

    - title: "Other Infrastructure Changes :gear:"
      labels:
        - infrastructure

    - title: "Other Changes :hammer_and_wrench:"
      labels:
        - "*"
