required_packages:
    - name: boat_simulator
      configs:
    - name: local_pathfinding
      configs:

inputs:
    - type:
      name:
      data:

expected_outputs:
    - type:
      name:
      data:
