required_packages:
    - name: boat_simulator
      configs:
    - name: network_systems
      configs:
      - example/example_en.yaml
      - mock_ais/mock_ais_en_default.yaml

inputs:
    - type:  ROS
      name:  /cached_fib
      data:
    - type: ROS
      name: /gps
      dtype: GPS
      data:
            lat_lon:
                dtype: HelperLatLon
                latitude: 1
                longitude: -1
            speed:
                dtype: HelperSpeed
                speed: 5
            heading:
                dtype: HelperHeading
                heading: 180

expected_outputs:
    - type:
      name:
      data:
