#!/bin/bash
# Perform necessary one-time setup for programs/scripts that need to run on boot
# Must be run as root

get_can_setup_service_content()
{
    EXEC_START_PATH=$1
    echo "\
        # DO NOT EDIT - generated by sailbot_workspace/.devcontainer/deployment/setup.sh
        [Unit]
        Description=CAN setup service

        [Service]
        ExecStart="$EXEC_START_PATH"

        [Install]
        WantedBy=multi-user.target
    "
}

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
SETUP_CAN_SCRIPT_PATH="$(readlink -f $SCRIPT_DIR/helpers/setup_can.sh)"
SERVICE_DIR="/etc/systemd/system"
SETUP_CAN_SERVICE="setup_can"
SETUP_CAN_SERVICE_PATH="$SERVICE_DIR/$SETUP_CAN_SERVICE.service"

echo "$(get_can_setup_service_content $SETUP_CAN_SCRIPT_PATH)" > $SETUP_CAN_SERVICE_PATH
systemctl start $SETUP_CAN_SERVICE
systemctl enable $SETUP_CAN_SERVICE
