export default class SalinitySensorsActions {
  static POLL_SALINITYSENSORS = 'POLL_SALINITYSENSORS';
  static REQUEST_SALINITYSENSORS_SUCCESS = 'REQUEST_SALINITYSENSORS_SUCCESS';
  static REQUEST_SALINITYSENSORS_FAILURE = 'REQUEST_SALINITYSENSORS_FAILURE';
}
