name: 'Checkout Repositories'
description: 'Checkout the repositories depending on the inputs'

inputs:
  repository:
    description: 'The repository name: github.event.repository.name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout ROS package
      if: ${{ inputs.repository != 'sailbot_workspace' }}
      uses: actions/checkout@v4
      with:
          repository: UBCSailbot/${{ inputs.repository }}
          path: src/${{ inputs.repository }}

    - name: Checkout custom_interfaces ROS package
      if: ${{ inputs.repository != 'sailbot_workspace' && inputs.repository != 'custom_interfaces' }}
      uses: actions/checkout@v4
      with:
          repository: UBCSailbot/custom_interfaces
          path: src/custom_interfaces

    - name: Checkout network_systems ROS package
      if: ${{ inputs.repository != 'sailbot_workspace' && inputs.repository == 'local_pathfinding' }}
      uses: actions/checkout@v4
      with:
          repository: UBCSailbot/network_systems
          path: src/network_systems

    - name: Checkout website ROS package
      if: ${{ inputs.repository != 'sailbot_workspace' && inputs.repository == 'local_pathfinding' }}
      uses: actions/checkout@v4
      with:
          repository: UBCSailbot/website
          path: src/website

    - name: Checkout virtual_iridium repository
      if: ${{ inputs.repository != 'sailbot_workspace' && inputs.repository == 'network_systems' }}
      uses: actions/checkout@v4
      with:
          repository: UBCSailbot/virtual_iridium
          path: src/virtual_iridium
