name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# Cancel in-progress runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # CI for all UBCSailbot repositories defined in one place
  # Runs another workflow: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
  test-definitions:
    # sailbot_workspace: use locally-defined file
    # other repositories: set to UBCSailbot/sailbot_workspace/.github/workflows/test_definitions.yml@<release>
    uses: UBCSailbot/sailbot_workspace/.github/workflows/test_definitions.yml@v1.7.0
    # see https://github.com/UBCSailbot/sailbot_workspace/blob/main/.github/workflows/test_definitions.yml
    # for documentation on the inputs and secrets below
    with:
      repository: ${{ github.event.repository.name }}
      ros-ci: true
      clang-tidy: true
      rebuild-docs: true
    # If rebuild-docs is true:
    # 1. Create the repository secret PAT_TOKEN (copy from Bitwarden)
    # 2. Uncomment the 2 lines below
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
