#!/bin/bash

# A simple shell script that takes as input a text file of names and converts them to
# C++ constants in a header file (network_systems/lib/cmn_hdrs/ros_info.h)
# REQUIREMENTS:
#    - A text document with the names of required ROS topics.
#    - Example use in command line: 
#          ./autogen_ros_topics.sh input.txt

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
OUTPUT_PATH=$SCRIPT_DIR/../lib/cmn_hdrs/ros_info.h

# Checks that requirements above are fulfilled.
if [ $# -ne 1 ]; then
  echo "Usage: $0 INPUT_FILE"
  exit 1
fi

INPUT_FILE=$1

echo "// AUTOGENERATED FILE - DO NOT EDIT" > $OUTPUT_PATH
echo "#pragma once" >> $OUTPUT_PATH

# Reads each line in the input text document
# Generates the name of the constant in required format
# Writes to output a C++ constant with the generated name and line
while read -r line; do
  CAPITALIZED=$(echo $line | tr '[:lower:]' '[:upper:]')
  VAR_NAME="${CAPITALIZED}_TOPIC"
  echo "constexpr auto $VAR_NAME = \"$line\";" >> $OUTPUT_PATH
done < "$INPUT_FILE"
