import argparse
import os

import yaml

NET_DIR = os.path.join(
    os.getenv("ROS_WORKSPACE", default="/workspaces/sailbot_workspace"), "src/network_systems"
)
ROS_INFO_FILE = os.path.join(NET_DIR, "ros_info.yaml")

GEN_CPP_MODULE_FILE = os.path.join(NET_DIR, "lib/cmn_hdrs/ros_info.cppm")
GEN_FILE_WARN = f"FILE GENERATED BY {__file__} using {ROS_INFO_FILE} - DO NOT EDIT"

GEN_CPP_MODULE_PREAMBLE = f"""
// {GEN_FILE_WARN}
module;

export module network_systems.ros_info;

export {{
"""
GEN_CPP_MODULE_TOPICS_START = """
namespace ros_topics
{
"""
GEN_CPP_MODULE_TOPICS_END = "}; // namespace ros_topics\n"
GEN_CPP_MODULE_NODES_START = """
namespace ros_nodes
{
"""
GEN_CPP_MODULE_NODES_END = "}; // namespace ros_nodes\n"
GEN_CPP_MODULE_END = "\n} // export\n"

GEN_PYTHON_FILE = os.path.join(NET_DIR, "launch/ros_info.py")
GEN_PYTHON_PREAMBLE = f"# {GEN_FILE_WARN} # noqa: E501\n"


def populate_cpp_module(module_file_obj, info_target):
    for k, v in info_target.items():
        module_file_obj.write(f'inline constexpr auto {k} = "{v}";\n')


def populate_py_nodes(py_file_obj, info_target):
    for k, v in info_target.items():
        py_file_obj.write(f'{k}_NODE = "{v}"\n')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cpp-output", default=GEN_CPP_MODULE_FILE)
    args = parser.parse_args()

    with open(ROS_INFO_FILE, "r") as f:
        info = yaml.safe_load(f)

        with open(args.cpp_output, "w+") as out_module:
            out_module.write(GEN_CPP_MODULE_PREAMBLE)

            out_module.write(GEN_CPP_MODULE_TOPICS_START)
            populate_cpp_module(out_module, info["ros_topics"])
            out_module.write(GEN_CPP_MODULE_TOPICS_END)

            out_module.write(GEN_CPP_MODULE_NODES_START)
            populate_cpp_module(out_module, info["ros_nodes"])
            out_module.write(GEN_CPP_MODULE_NODES_END)
            out_module.write(GEN_CPP_MODULE_END)

        with open(GEN_PYTHON_FILE, "w+") as out_py:
            out_py.write(GEN_PYTHON_PREAMBLE)
            populate_py_nodes(out_py, info["ros_nodes"])


if __name__ == "__main__":
    main()
