#!/usr/bin/bash
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
TESTPLAN_DIR=$SCRIPT_DIR/../testplans
TESTPLANS=$(ls $TESTPLAN_DIR | grep ".yaml")

for TESTPLAN in $TESTPLANS
do
    INFILE=$TESTPLAN_DIR/$TESTPLAN
    OUTFILE=$SCRIPT_DIR/$TESTPLAN
    echo "# AUTOGENERATED FILE - DO NOT EDIT" > $OUTFILE
    echo "# ROS launch config wrapper for $INFILE" >> $OUTFILE
    echo "integration_test_node:" >> $OUTFILE
    echo "  ros__parameters:" >> $OUTFILE
    echo "    testplan: $(readlink -f $INFILE)" >> $OUTFILE
done
