name: 'Ament Lint'
description: 'Ament Lint using devcontainer'

inputs:
  linter:
    description: 'The linter to run'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Containers
      shell: bash
      run: docker compose -f .devcontainer/docker-compose.yml build

    - name: Run Containers
      shell: bash
      run: docker compose -f .devcontainer/docker-compose.yml up -d

    - name: Run Tests
      shell: bash
      run: docker compose -f .devcontainer/docker-compose.yml exec -T sailbot-workspace /bin/bash -c "export LINTER=${{ inputs.linter}} && cd /workspaces/sailbot_workspace && .github/actions/ament-lint/run.sh"
