export default class DataFilterActions {
  static SET_TIMESTAMP = 'SET_TIMESTAMP';
  static SET_TIMESTAMP_SUCCESS = 'SET_TIMESTAMP_SUCCESS';
  static SET_TIMESTAMP_FAILURE = 'SET_TIMESTAMP_FAILURE';
}
