# Template for the local_transceiver module
local_transceiver_node:
  ros__parameters:
    enabled: true
    # The following parameters are optional. Defaults are set in local_transceiver_ros_intf.cpp
    port: # String: Serial port that the Local Transceiver will use (default: /tmp/local_transceiver_test_port)

