# Template for the local_transceiver module
local_transceiver_node:
  ros__parameters:
    enabled: true
    # The following parameters are optional. Defaults are set in local_transceiver_ros_intf.cpp
    port: # Integer: Port that the Local Transceiver will use for the server (ex. 8081)
