# adapted from https://github.com/microsoft/vscode-dev-containers/blob/main/containers/javascript-node-mongo/.devcontainer/docker-compose.yml
# Note: the "ports" property in this file will not forward from a codespace; add to "forwardPorts" in devcontainer.json instead
version: '3.8'

services:
  sailbot-workspace:
    build:
      context: ../../.devcontainer
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONN_STR=mongodb://localhost:27017
    volumes:
      - ../..:/workspaces/sailbot_workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # From run arguments of template repository
    cap_add:
    - SYS_PTRACE
    security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
