export default class WindSensorsAction {
  static POLL_WINDSENSORS = 'POLL_WINDSENSORS';
  static REQUEST_WINDSENSORS_SUCCESS = 'REQUEST_WINDSENSORS_SUCCESS';
  static REQUEST_WINDSENSORS_FAILURE = 'REQUEST_WINDSENSORS_FAILURE';
}
