constants:
  tw_dir_deg: &dir -100
  tw_speed_kmph: &speed 100.0 # must be double

/mock_wind_sensor:
  ros__parameters:
    tw_dir_deg: *dir
    tw_speed_kmph: *speed

/mock_gps:
  ros__parameters:
    tw_speed_kmph: *speed
    tw_dir_deg: *dir
