export default class TempSensorsActions {
  static POLL_TEMPSENSORS = 'POLL_TEMPSENSORS';
  static REQUEST_TEMPSENSORS_SUCCESS = 'REQUEST_TEMPSENSORS_SUCCESS';
  static REQUEST_TEMPSENSORS_FAILURE = 'REQUEST_TEMPSENSORS_FAILURE';
}
