# adapted from https://github.com/microsoft/vscode-dev-containers/blob/main/containers/javascript-node-mongo/.devcontainer/docker-compose.yml
# Note: the "ports" property in this file will not forward from a codespace; add to "forwardPorts" in devcontainer.json instead
version: '3.8'

services:
  # URL: mongodb://localhost:27017
  mongodb:
    image: mongo:latest
    restart: unless-stopped

    # Runs on the same network as the workspace container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:sailbot-workspace

    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here
