export default class GlobalPathActions {
  static POLL_GLOBALPATH = 'POLL_GLOBALPATH';
  static REQUEST_GLOBALPATH_SUCCESS = 'REQUEST_GLOBALPATH_SUCCESS';
  static REQUEST_GLOBALPATH_FAILURE = 'REQUEST_GLOBALPATH_FAILURE';
}
