export default class AISShipsActions {
  static POLL_AISSHIPS = 'POLL_AISSHIPS';
  static REQUEST_AISSHIPS_SUCCESS = 'REQUEST_AISSHIPS_SUCCESS';
  static REQUEST_AISSHIPS_FAILURE = 'REQUEST_AISSHIPS_FAILURE';
}
