# Request: The desired position to turn to
# Unit: degrees, 0° is the neutral position, Increases CCW
# Range: -40° <= angle <= 40°
float32 desired_angular_position
---
# Result: The absolute angular distance between the current and desired heading
# Units: degrees
# Range: [0, 180] (TODO: Conform desireable range with MECH team)
float32 remaining_angular_distance
---
# Feedback: The trim tab angle with respect to the wingsail
# Unit: degrees, 0° is the neutral position, Increases CCW
# Range: -40° <= angle <= 40°
float32 current_angular_position
