export default class BatteriesActions {
  static POLL_BATTERIES = 'POLL_BATTERIES';
  static REQUEST_BATTERIES_SUCCESS = 'REQUEST_BATTERIES_SUCCESS';
  static REQUEST_BATTERIES_FAILURE = 'REQUEST_BATTERIES_FAILURE';
}
