name: 'Clang-Tidy'
description: 'Clang-Tidy using devcontainer'

inputs:
  disable_vcs:
    description: 'Whether to disable VCS cloning all repositories'
    required: true

runs:
  using: "composite"
  steps:
    - name: Build Containers
      shell: bash
      run: docker-compose -f .github/actions/docker-compose.ci.yml build

    - name: Run Containers
      shell: bash
      run: docker-compose -f .github/actions/docker-compose.ci.yml up -d

    - name: Run Tests
      shell: bash
      run: docker-compose -f .github/actions/docker-compose.ci.yml exec -T sailbot-workspace /bin/bash -c "export DISABLE_VCS=${{ inputs.disable_vcs }} && cd /workspaces/sailbot_workspace && .github/actions/clang-tidy/run.sh"
