export default class GenericSensorsActions {
  static POLL_GENERICSENSORS = 'POLL_GENERICSENSORS';
  static REQUEST_GENERICSENSORS_SUCCESS = 'REQUEST_GENERICSENSORS_SUCCESS';
  static REQUEST_GENERICSENSORS_FAILURE = 'REQUEST_GENERICSENSORS_FAILURE';
}
