export default class PhSensorsActions {
  static POLL_PHSENSORS = 'POLL_PHSENSORS';
  static REQUEST_PHSENSORS_SUCCESS = 'REQUEST_PHSENSORS_SUCCESS';
  static REQUEST_PHSENSORS_FAILURE = 'REQUEST_PHSENSORS_FAILURE';
}
