export default class TimestampActions {
  static TIMESTAMP = 'TIMESTAMP';
  static REQUEST_TIMESTAMP_SUCCESS = 'REQUEST_TIMESTAMP_SUCCESS';
  static REQUEST_TIMESTAMP_FAILURE = 'REQUEST_TIMESTAMP_FAILURE';
}
