# Rate of turn of the ship, negative for CCW (min -126) turning and positive for CW (max +126) turning.
# Special unit: https://documentation.spire.com/ais-fundamentals/understanding-ais-performance-in-high-traffic-zones/
# = int(4.733 * sqrt(degrees/minute))
# -126 and +126 indicate CCW/CW at a rate of up to 708 degrees/minute or higher
# -127 and +127 are special values indicates CCW/CW turning of more than 10 degrees/minute (only used if the reporting
# vessel does not have an external ROT indicator device available)
# -128 means no rot info
int8 rot
