// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global_path.proto

#include "global_path.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_waypoint_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Waypoint_waypoint_2eproto;
namespace Polaris {
class GlobalPathDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GlobalPath> _instance;
} _GlobalPath_default_instance_;
}  // namespace Polaris
static void InitDefaultsscc_info_GlobalPath_global_5fpath_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_GlobalPath_default_instance_;
    new (ptr) ::Polaris::GlobalPath();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::GlobalPath::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_GlobalPath_global_5fpath_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_GlobalPath_global_5fpath_2eproto}, {
      &scc_info_Waypoint_waypoint_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_global_5fpath_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_global_5fpath_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_global_5fpath_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_global_5fpath_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::GlobalPath, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::GlobalPath, num_waypoints_),
  PROTOBUF_FIELD_OFFSET(::Polaris::GlobalPath, waypoints_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Polaris::GlobalPath)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_GlobalPath_default_instance_),
};

const char descriptor_table_protodef_global_5fpath_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021global_path.proto\022\007Polaris\032\016waypoint.p"
  "roto\"I\n\nGlobalPath\022\025\n\rnum_waypoints\030\001 \001("
  "\r\022$\n\twaypoints\030\002 \003(\0132\021.Polaris.Waypointb"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_global_5fpath_2eproto_deps[1] = {
  &::descriptor_table_waypoint_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_global_5fpath_2eproto_sccs[1] = {
  &scc_info_GlobalPath_global_5fpath_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_global_5fpath_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_global_5fpath_2eproto = {
  false, false, descriptor_table_protodef_global_5fpath_2eproto, "global_path.proto", 127,
  &descriptor_table_global_5fpath_2eproto_once, descriptor_table_global_5fpath_2eproto_sccs, descriptor_table_global_5fpath_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_global_5fpath_2eproto::offsets,
  file_level_metadata_global_5fpath_2eproto, 1, file_level_enum_descriptors_global_5fpath_2eproto, file_level_service_descriptors_global_5fpath_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_global_5fpath_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_global_5fpath_2eproto)), true);
namespace Polaris {

// ===================================================================

void GlobalPath::InitAsDefaultInstance() {
}
class GlobalPath::_Internal {
 public:
};

void GlobalPath::clear_waypoints() {
  waypoints_.Clear();
}
GlobalPath::GlobalPath(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  waypoints_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.GlobalPath)
}
GlobalPath::GlobalPath(const GlobalPath& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      waypoints_(from.waypoints_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  num_waypoints_ = from.num_waypoints_;
  // @@protoc_insertion_point(copy_constructor:Polaris.GlobalPath)
}

void GlobalPath::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GlobalPath_global_5fpath_2eproto.base);
  num_waypoints_ = 0u;
}

GlobalPath::~GlobalPath() {
  // @@protoc_insertion_point(destructor:Polaris.GlobalPath)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void GlobalPath::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void GlobalPath::ArenaDtor(void* object) {
  GlobalPath* _this = reinterpret_cast< GlobalPath* >(object);
  (void)_this;
}
void GlobalPath::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GlobalPath::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GlobalPath& GlobalPath::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GlobalPath_global_5fpath_2eproto.base);
  return *internal_default_instance();
}


void GlobalPath::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.GlobalPath)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  waypoints_.Clear();
  num_waypoints_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GlobalPath::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 num_waypoints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          num_waypoints_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .Polaris.Waypoint waypoints = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_waypoints(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* GlobalPath::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.GlobalPath)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 num_waypoints = 1;
  if (this->num_waypoints() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_num_waypoints(), target);
  }

  // repeated .Polaris.Waypoint waypoints = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_waypoints_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_waypoints(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.GlobalPath)
  return target;
}

size_t GlobalPath::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.GlobalPath)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Polaris.Waypoint waypoints = 2;
  total_size += 1UL * this->_internal_waypoints_size();
  for (const auto& msg : this->waypoints_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 num_waypoints = 1;
  if (this->num_waypoints() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_num_waypoints());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GlobalPath::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.GlobalPath)
  GOOGLE_DCHECK_NE(&from, this);
  const GlobalPath* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GlobalPath>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.GlobalPath)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.GlobalPath)
    MergeFrom(*source);
  }
}

void GlobalPath::MergeFrom(const GlobalPath& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.GlobalPath)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  waypoints_.MergeFrom(from.waypoints_);
  if (from.num_waypoints() != 0) {
    _internal_set_num_waypoints(from._internal_num_waypoints());
  }
}

void GlobalPath::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.GlobalPath)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GlobalPath::CopyFrom(const GlobalPath& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.GlobalPath)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GlobalPath::IsInitialized() const {
  return true;
}

void GlobalPath::InternalSwap(GlobalPath* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  waypoints_.InternalSwap(&other->waypoints_);
  swap(num_waypoints_, other->num_waypoints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GlobalPath::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Polaris
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Polaris::GlobalPath* Arena::CreateMaybeMessage< ::Polaris::GlobalPath >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::GlobalPath >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
