// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensors.proto

#include "sensors.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_sensors_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Ais_sensors_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_sensors_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Battery_sensors_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_sensors_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Gps_sensors_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_sensors_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Sensors_Path_sensors_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_sensors_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Wind_sensors_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_waypoint_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Waypoint_waypoint_2eproto;
namespace Polaris {
class Sensors_GpsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Sensors_Gps> _instance;
} _Sensors_Gps_default_instance_;
class Sensors_WindDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Sensors_Wind> _instance;
} _Sensors_Wind_default_instance_;
class Sensors_BatteryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Sensors_Battery> _instance;
} _Sensors_Battery_default_instance_;
class Sensors_AisDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Sensors_Ais> _instance;
} _Sensors_Ais_default_instance_;
class Sensors_GenericDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Sensors_Generic> _instance;
} _Sensors_Generic_default_instance_;
class Sensors_PathDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Sensors_Path> _instance;
} _Sensors_Path_default_instance_;
class SensorsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Sensors> _instance;
} _Sensors_default_instance_;
}  // namespace Polaris
static void InitDefaultsscc_info_Sensors_sensors_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_Sensors_default_instance_;
    new (ptr) ::Polaris::Sensors();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::Sensors::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<5> scc_info_Sensors_sensors_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 5, 0, InitDefaultsscc_info_Sensors_sensors_2eproto}, {
      &scc_info_Sensors_Gps_sensors_2eproto.base,
      &scc_info_Sensors_Wind_sensors_2eproto.base,
      &scc_info_Sensors_Battery_sensors_2eproto.base,
      &scc_info_Sensors_Ais_sensors_2eproto.base,
      &scc_info_Sensors_Path_sensors_2eproto.base,}};

static void InitDefaultsscc_info_Sensors_Ais_sensors_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_Sensors_Ais_default_instance_;
    new (ptr) ::Polaris::Sensors_Ais();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::Sensors_Ais::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Ais_sensors_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Sensors_Ais_sensors_2eproto}, {}};

static void InitDefaultsscc_info_Sensors_Battery_sensors_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_Sensors_Battery_default_instance_;
    new (ptr) ::Polaris::Sensors_Battery();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::Sensors_Battery::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Battery_sensors_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Sensors_Battery_sensors_2eproto}, {}};

static void InitDefaultsscc_info_Sensors_Generic_sensors_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_Sensors_Generic_default_instance_;
    new (ptr) ::Polaris::Sensors_Generic();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::Sensors_Generic::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Generic_sensors_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Sensors_Generic_sensors_2eproto}, {}};

static void InitDefaultsscc_info_Sensors_Gps_sensors_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_Sensors_Gps_default_instance_;
    new (ptr) ::Polaris::Sensors_Gps();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::Sensors_Gps::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Gps_sensors_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Sensors_Gps_sensors_2eproto}, {}};

static void InitDefaultsscc_info_Sensors_Path_sensors_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_Sensors_Path_default_instance_;
    new (ptr) ::Polaris::Sensors_Path();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::Sensors_Path::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Sensors_Path_sensors_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_Sensors_Path_sensors_2eproto}, {
      &scc_info_Waypoint_waypoint_2eproto.base,}};

static void InitDefaultsscc_info_Sensors_Wind_sensors_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Polaris::_Sensors_Wind_default_instance_;
    new (ptr) ::Polaris::Sensors_Wind();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Polaris::Sensors_Wind::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Sensors_Wind_sensors_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Sensors_Wind_sensors_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_sensors_2eproto[7];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_sensors_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_sensors_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_sensors_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Gps, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Gps, latitude_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Gps, longitude_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Gps, speed_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Gps, heading_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Wind, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Wind, speed_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Wind, direction_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Battery, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Battery, voltage_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Battery, current_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, id_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, latitude_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, longitude_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, sog_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, cog_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, rot_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, width_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Ais, length_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Generic, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Generic, id_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Generic, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Path, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors_Path, waypoints_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, gps_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, wind_sensors_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, batteries_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, ais_ships_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, temp_sensors_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, ph_sensors_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, salinity_sensors_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, pressure_sensors_),
  PROTOBUF_FIELD_OFFSET(::Polaris::Sensors, local_path_data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Polaris::Sensors_Gps)},
  { 9, -1, sizeof(::Polaris::Sensors_Wind)},
  { 16, -1, sizeof(::Polaris::Sensors_Battery)},
  { 23, -1, sizeof(::Polaris::Sensors_Ais)},
  { 36, -1, sizeof(::Polaris::Sensors_Generic)},
  { 43, -1, sizeof(::Polaris::Sensors_Path)},
  { 49, -1, sizeof(::Polaris::Sensors)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_Sensors_Gps_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_Sensors_Wind_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_Sensors_Battery_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_Sensors_Ais_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_Sensors_Generic_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_Sensors_Path_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Polaris::_Sensors_default_instance_),
};

const char descriptor_table_protodef_sensors_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rsensors.proto\022\007Polaris\032\016waypoint.proto"
  "\"\261\005\n\007Sensors\022!\n\003gps\030\001 \001(\0132\024.Polaris.Sens"
  "ors.Gps\022+\n\014wind_sensors\030\002 \003(\0132\025.Polaris."
  "Sensors.Wind\022+\n\tbatteries\030\003 \003(\0132\030.Polari"
  "s.Sensors.Battery\022\'\n\tais_ships\030\004 \003(\0132\024.P"
  "olaris.Sensors.Ais\022\024\n\014temp_sensors\030\005 \003(\002"
  "\022\022\n\nph_sensors\030\006 \003(\002\022\030\n\020salinity_sensors"
  "\030\007 \003(\002\022\030\n\020pressure_sensors\030\010 \003(\002\022.\n\017loca"
  "l_path_data\030\t \001(\0132\025.Polaris.Sensors.Path"
  "\032J\n\003Gps\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlongitude\030\002"
  " \001(\002\022\r\n\005speed\030\003 \001(\002\022\017\n\007heading\030\004 \001(\002\032(\n\004"
  "Wind\022\r\n\005speed\030\001 \001(\002\022\021\n\tdirection\030\002 \001(\005\032+"
  "\n\007Battery\022\017\n\007voltage\030\001 \001(\002\022\017\n\007current\030\002 "
  "\001(\002\032|\n\003Ais\022\n\n\002id\030\001 \001(\r\022\020\n\010latitude\030\002 \001(\002"
  "\022\021\n\tlongitude\030\003 \001(\002\022\013\n\003sog\030\004 \001(\002\022\013\n\003cog\030"
  "\005 \001(\002\022\013\n\003rot\030\006 \001(\002\022\r\n\005width\030\007 \001(\002\022\016\n\006len"
  "gth\030\010 \001(\002\032#\n\007Generic\022\n\n\002id\030\001 \001(\r\022\014\n\004data"
  "\030\002 \001(\004\032,\n\004Path\022$\n\twaypoints\030\001 \003(\0132\021.Pola"
  "ris.Waypointb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_sensors_2eproto_deps[1] = {
  &::descriptor_table_waypoint_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_sensors_2eproto_sccs[7] = {
  &scc_info_Sensors_sensors_2eproto.base,
  &scc_info_Sensors_Ais_sensors_2eproto.base,
  &scc_info_Sensors_Battery_sensors_2eproto.base,
  &scc_info_Sensors_Generic_sensors_2eproto.base,
  &scc_info_Sensors_Gps_sensors_2eproto.base,
  &scc_info_Sensors_Path_sensors_2eproto.base,
  &scc_info_Sensors_Wind_sensors_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_sensors_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sensors_2eproto = {
  false, false, descriptor_table_protodef_sensors_2eproto, "sensors.proto", 740,
  &descriptor_table_sensors_2eproto_once, descriptor_table_sensors_2eproto_sccs, descriptor_table_sensors_2eproto_deps, 7, 1,
  schemas, file_default_instances, TableStruct_sensors_2eproto::offsets,
  file_level_metadata_sensors_2eproto, 7, file_level_enum_descriptors_sensors_2eproto, file_level_service_descriptors_sensors_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_sensors_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_sensors_2eproto)), true);
namespace Polaris {

// ===================================================================

void Sensors_Gps::InitAsDefaultInstance() {
}
class Sensors_Gps::_Internal {
 public:
};

Sensors_Gps::Sensors_Gps(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.Sensors.Gps)
}
Sensors_Gps::Sensors_Gps(const Sensors_Gps& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&latitude_, &from.latitude_,
    static_cast<size_t>(reinterpret_cast<char*>(&heading_) -
    reinterpret_cast<char*>(&latitude_)) + sizeof(heading_));
  // @@protoc_insertion_point(copy_constructor:Polaris.Sensors.Gps)
}

void Sensors_Gps::SharedCtor() {
  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&heading_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(heading_));
}

Sensors_Gps::~Sensors_Gps() {
  // @@protoc_insertion_point(destructor:Polaris.Sensors.Gps)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Sensors_Gps::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Sensors_Gps::ArenaDtor(void* object) {
  Sensors_Gps* _this = reinterpret_cast< Sensors_Gps* >(object);
  (void)_this;
}
void Sensors_Gps::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Sensors_Gps::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Sensors_Gps& Sensors_Gps::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Sensors_Gps_sensors_2eproto.base);
  return *internal_default_instance();
}


void Sensors_Gps::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.Sensors.Gps)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&latitude_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&heading_) -
      reinterpret_cast<char*>(&latitude_)) + sizeof(heading_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sensors_Gps::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float latitude = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float longitude = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float speed = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float heading = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          heading_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Sensors_Gps::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.Sensors.Gps)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float latitude = 1;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_latitude(), target);
  }

  // float longitude = 2;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_longitude(), target);
  }

  // float speed = 3;
  if (!(this->speed() <= 0 && this->speed() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_speed(), target);
  }

  // float heading = 4;
  if (!(this->heading() <= 0 && this->heading() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_heading(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.Sensors.Gps)
  return target;
}

size_t Sensors_Gps::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.Sensors.Gps)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float latitude = 1;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    total_size += 1 + 4;
  }

  // float longitude = 2;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    total_size += 1 + 4;
  }

  // float speed = 3;
  if (!(this->speed() <= 0 && this->speed() >= 0)) {
    total_size += 1 + 4;
  }

  // float heading = 4;
  if (!(this->heading() <= 0 && this->heading() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Sensors_Gps::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.Sensors.Gps)
  GOOGLE_DCHECK_NE(&from, this);
  const Sensors_Gps* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Sensors_Gps>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.Sensors.Gps)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.Sensors.Gps)
    MergeFrom(*source);
  }
}

void Sensors_Gps::MergeFrom(const Sensors_Gps& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.Sensors.Gps)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.latitude() <= 0 && from.latitude() >= 0)) {
    _internal_set_latitude(from._internal_latitude());
  }
  if (!(from.longitude() <= 0 && from.longitude() >= 0)) {
    _internal_set_longitude(from._internal_longitude());
  }
  if (!(from.speed() <= 0 && from.speed() >= 0)) {
    _internal_set_speed(from._internal_speed());
  }
  if (!(from.heading() <= 0 && from.heading() >= 0)) {
    _internal_set_heading(from._internal_heading());
  }
}

void Sensors_Gps::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.Sensors.Gps)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sensors_Gps::CopyFrom(const Sensors_Gps& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.Sensors.Gps)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sensors_Gps::IsInitialized() const {
  return true;
}

void Sensors_Gps::InternalSwap(Sensors_Gps* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sensors_Gps, heading_)
      + sizeof(Sensors_Gps::heading_)
      - PROTOBUF_FIELD_OFFSET(Sensors_Gps, latitude_)>(
          reinterpret_cast<char*>(&latitude_),
          reinterpret_cast<char*>(&other->latitude_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Sensors_Gps::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Sensors_Wind::InitAsDefaultInstance() {
}
class Sensors_Wind::_Internal {
 public:
};

Sensors_Wind::Sensors_Wind(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.Sensors.Wind)
}
Sensors_Wind::Sensors_Wind(const Sensors_Wind& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&speed_, &from.speed_,
    static_cast<size_t>(reinterpret_cast<char*>(&direction_) -
    reinterpret_cast<char*>(&speed_)) + sizeof(direction_));
  // @@protoc_insertion_point(copy_constructor:Polaris.Sensors.Wind)
}

void Sensors_Wind::SharedCtor() {
  ::memset(&speed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&direction_) -
      reinterpret_cast<char*>(&speed_)) + sizeof(direction_));
}

Sensors_Wind::~Sensors_Wind() {
  // @@protoc_insertion_point(destructor:Polaris.Sensors.Wind)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Sensors_Wind::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Sensors_Wind::ArenaDtor(void* object) {
  Sensors_Wind* _this = reinterpret_cast< Sensors_Wind* >(object);
  (void)_this;
}
void Sensors_Wind::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Sensors_Wind::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Sensors_Wind& Sensors_Wind::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Sensors_Wind_sensors_2eproto.base);
  return *internal_default_instance();
}


void Sensors_Wind::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.Sensors.Wind)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&speed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&direction_) -
      reinterpret_cast<char*>(&speed_)) + sizeof(direction_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sensors_Wind::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float speed = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // int32 direction = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          direction_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Sensors_Wind::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.Sensors.Wind)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float speed = 1;
  if (!(this->speed() <= 0 && this->speed() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_speed(), target);
  }

  // int32 direction = 2;
  if (this->direction() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_direction(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.Sensors.Wind)
  return target;
}

size_t Sensors_Wind::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.Sensors.Wind)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float speed = 1;
  if (!(this->speed() <= 0 && this->speed() >= 0)) {
    total_size += 1 + 4;
  }

  // int32 direction = 2;
  if (this->direction() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_direction());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Sensors_Wind::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.Sensors.Wind)
  GOOGLE_DCHECK_NE(&from, this);
  const Sensors_Wind* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Sensors_Wind>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.Sensors.Wind)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.Sensors.Wind)
    MergeFrom(*source);
  }
}

void Sensors_Wind::MergeFrom(const Sensors_Wind& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.Sensors.Wind)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.speed() <= 0 && from.speed() >= 0)) {
    _internal_set_speed(from._internal_speed());
  }
  if (from.direction() != 0) {
    _internal_set_direction(from._internal_direction());
  }
}

void Sensors_Wind::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.Sensors.Wind)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sensors_Wind::CopyFrom(const Sensors_Wind& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.Sensors.Wind)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sensors_Wind::IsInitialized() const {
  return true;
}

void Sensors_Wind::InternalSwap(Sensors_Wind* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sensors_Wind, direction_)
      + sizeof(Sensors_Wind::direction_)
      - PROTOBUF_FIELD_OFFSET(Sensors_Wind, speed_)>(
          reinterpret_cast<char*>(&speed_),
          reinterpret_cast<char*>(&other->speed_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Sensors_Wind::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Sensors_Battery::InitAsDefaultInstance() {
}
class Sensors_Battery::_Internal {
 public:
};

Sensors_Battery::Sensors_Battery(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.Sensors.Battery)
}
Sensors_Battery::Sensors_Battery(const Sensors_Battery& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&voltage_, &from.voltage_,
    static_cast<size_t>(reinterpret_cast<char*>(&current_) -
    reinterpret_cast<char*>(&voltage_)) + sizeof(current_));
  // @@protoc_insertion_point(copy_constructor:Polaris.Sensors.Battery)
}

void Sensors_Battery::SharedCtor() {
  ::memset(&voltage_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&current_) -
      reinterpret_cast<char*>(&voltage_)) + sizeof(current_));
}

Sensors_Battery::~Sensors_Battery() {
  // @@protoc_insertion_point(destructor:Polaris.Sensors.Battery)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Sensors_Battery::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Sensors_Battery::ArenaDtor(void* object) {
  Sensors_Battery* _this = reinterpret_cast< Sensors_Battery* >(object);
  (void)_this;
}
void Sensors_Battery::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Sensors_Battery::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Sensors_Battery& Sensors_Battery::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Sensors_Battery_sensors_2eproto.base);
  return *internal_default_instance();
}


void Sensors_Battery::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.Sensors.Battery)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&voltage_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&current_) -
      reinterpret_cast<char*>(&voltage_)) + sizeof(current_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sensors_Battery::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float voltage = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          voltage_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float current = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          current_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Sensors_Battery::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.Sensors.Battery)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float voltage = 1;
  if (!(this->voltage() <= 0 && this->voltage() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_voltage(), target);
  }

  // float current = 2;
  if (!(this->current() <= 0 && this->current() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_current(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.Sensors.Battery)
  return target;
}

size_t Sensors_Battery::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.Sensors.Battery)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float voltage = 1;
  if (!(this->voltage() <= 0 && this->voltage() >= 0)) {
    total_size += 1 + 4;
  }

  // float current = 2;
  if (!(this->current() <= 0 && this->current() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Sensors_Battery::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.Sensors.Battery)
  GOOGLE_DCHECK_NE(&from, this);
  const Sensors_Battery* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Sensors_Battery>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.Sensors.Battery)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.Sensors.Battery)
    MergeFrom(*source);
  }
}

void Sensors_Battery::MergeFrom(const Sensors_Battery& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.Sensors.Battery)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.voltage() <= 0 && from.voltage() >= 0)) {
    _internal_set_voltage(from._internal_voltage());
  }
  if (!(from.current() <= 0 && from.current() >= 0)) {
    _internal_set_current(from._internal_current());
  }
}

void Sensors_Battery::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.Sensors.Battery)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sensors_Battery::CopyFrom(const Sensors_Battery& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.Sensors.Battery)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sensors_Battery::IsInitialized() const {
  return true;
}

void Sensors_Battery::InternalSwap(Sensors_Battery* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sensors_Battery, current_)
      + sizeof(Sensors_Battery::current_)
      - PROTOBUF_FIELD_OFFSET(Sensors_Battery, voltage_)>(
          reinterpret_cast<char*>(&voltage_),
          reinterpret_cast<char*>(&other->voltage_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Sensors_Battery::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Sensors_Ais::InitAsDefaultInstance() {
}
class Sensors_Ais::_Internal {
 public:
};

Sensors_Ais::Sensors_Ais(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.Sensors.Ais)
}
Sensors_Ais::Sensors_Ais(const Sensors_Ais& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&length_) -
    reinterpret_cast<char*>(&id_)) + sizeof(length_));
  // @@protoc_insertion_point(copy_constructor:Polaris.Sensors.Ais)
}

void Sensors_Ais::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&length_) -
      reinterpret_cast<char*>(&id_)) + sizeof(length_));
}

Sensors_Ais::~Sensors_Ais() {
  // @@protoc_insertion_point(destructor:Polaris.Sensors.Ais)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Sensors_Ais::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Sensors_Ais::ArenaDtor(void* object) {
  Sensors_Ais* _this = reinterpret_cast< Sensors_Ais* >(object);
  (void)_this;
}
void Sensors_Ais::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Sensors_Ais::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Sensors_Ais& Sensors_Ais::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Sensors_Ais_sensors_2eproto.base);
  return *internal_default_instance();
}


void Sensors_Ais::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.Sensors.Ais)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&length_) -
      reinterpret_cast<char*>(&id_)) + sizeof(length_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sensors_Ais::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float latitude = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          latitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float longitude = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          longitude_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float sog = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          sog_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float cog = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          cog_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float rot = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53)) {
          rot_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float width = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          width_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float length = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          length_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Sensors_Ais::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.Sensors.Ais)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_id(), target);
  }

  // float latitude = 2;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_latitude(), target);
  }

  // float longitude = 3;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_longitude(), target);
  }

  // float sog = 4;
  if (!(this->sog() <= 0 && this->sog() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_sog(), target);
  }

  // float cog = 5;
  if (!(this->cog() <= 0 && this->cog() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_cog(), target);
  }

  // float rot = 6;
  if (!(this->rot() <= 0 && this->rot() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_rot(), target);
  }

  // float width = 7;
  if (!(this->width() <= 0 && this->width() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->_internal_width(), target);
  }

  // float length = 8;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->_internal_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.Sensors.Ais)
  return target;
}

size_t Sensors_Ais::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.Sensors.Ais)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_id());
  }

  // float latitude = 2;
  if (!(this->latitude() <= 0 && this->latitude() >= 0)) {
    total_size += 1 + 4;
  }

  // float longitude = 3;
  if (!(this->longitude() <= 0 && this->longitude() >= 0)) {
    total_size += 1 + 4;
  }

  // float sog = 4;
  if (!(this->sog() <= 0 && this->sog() >= 0)) {
    total_size += 1 + 4;
  }

  // float cog = 5;
  if (!(this->cog() <= 0 && this->cog() >= 0)) {
    total_size += 1 + 4;
  }

  // float rot = 6;
  if (!(this->rot() <= 0 && this->rot() >= 0)) {
    total_size += 1 + 4;
  }

  // float width = 7;
  if (!(this->width() <= 0 && this->width() >= 0)) {
    total_size += 1 + 4;
  }

  // float length = 8;
  if (!(this->length() <= 0 && this->length() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Sensors_Ais::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.Sensors.Ais)
  GOOGLE_DCHECK_NE(&from, this);
  const Sensors_Ais* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Sensors_Ais>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.Sensors.Ais)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.Sensors.Ais)
    MergeFrom(*source);
  }
}

void Sensors_Ais::MergeFrom(const Sensors_Ais& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.Sensors.Ais)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
  if (!(from.latitude() <= 0 && from.latitude() >= 0)) {
    _internal_set_latitude(from._internal_latitude());
  }
  if (!(from.longitude() <= 0 && from.longitude() >= 0)) {
    _internal_set_longitude(from._internal_longitude());
  }
  if (!(from.sog() <= 0 && from.sog() >= 0)) {
    _internal_set_sog(from._internal_sog());
  }
  if (!(from.cog() <= 0 && from.cog() >= 0)) {
    _internal_set_cog(from._internal_cog());
  }
  if (!(from.rot() <= 0 && from.rot() >= 0)) {
    _internal_set_rot(from._internal_rot());
  }
  if (!(from.width() <= 0 && from.width() >= 0)) {
    _internal_set_width(from._internal_width());
  }
  if (!(from.length() <= 0 && from.length() >= 0)) {
    _internal_set_length(from._internal_length());
  }
}

void Sensors_Ais::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.Sensors.Ais)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sensors_Ais::CopyFrom(const Sensors_Ais& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.Sensors.Ais)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sensors_Ais::IsInitialized() const {
  return true;
}

void Sensors_Ais::InternalSwap(Sensors_Ais* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sensors_Ais, length_)
      + sizeof(Sensors_Ais::length_)
      - PROTOBUF_FIELD_OFFSET(Sensors_Ais, id_)>(
          reinterpret_cast<char*>(&id_),
          reinterpret_cast<char*>(&other->id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Sensors_Ais::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Sensors_Generic::InitAsDefaultInstance() {
}
class Sensors_Generic::_Internal {
 public:
};

Sensors_Generic::Sensors_Generic(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.Sensors.Generic)
}
Sensors_Generic::Sensors_Generic(const Sensors_Generic& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&data_, &from.data_,
    static_cast<size_t>(reinterpret_cast<char*>(&id_) -
    reinterpret_cast<char*>(&data_)) + sizeof(id_));
  // @@protoc_insertion_point(copy_constructor:Polaris.Sensors.Generic)
}

void Sensors_Generic::SharedCtor() {
  ::memset(&data_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&data_)) + sizeof(id_));
}

Sensors_Generic::~Sensors_Generic() {
  // @@protoc_insertion_point(destructor:Polaris.Sensors.Generic)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Sensors_Generic::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Sensors_Generic::ArenaDtor(void* object) {
  Sensors_Generic* _this = reinterpret_cast< Sensors_Generic* >(object);
  (void)_this;
}
void Sensors_Generic::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Sensors_Generic::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Sensors_Generic& Sensors_Generic::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Sensors_Generic_sensors_2eproto.base);
  return *internal_default_instance();
}


void Sensors_Generic::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.Sensors.Generic)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&data_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&id_) -
      reinterpret_cast<char*>(&data_)) + sizeof(id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sensors_Generic::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          data_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Sensors_Generic::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.Sensors.Generic)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_id(), target);
  }

  // uint64 data = 2;
  if (this->data() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(2, this->_internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.Sensors.Generic)
  return target;
}

size_t Sensors_Generic::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.Sensors.Generic)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 data = 2;
  if (this->data() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_data());
  }

  // uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Sensors_Generic::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.Sensors.Generic)
  GOOGLE_DCHECK_NE(&from, this);
  const Sensors_Generic* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Sensors_Generic>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.Sensors.Generic)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.Sensors.Generic)
    MergeFrom(*source);
  }
}

void Sensors_Generic::MergeFrom(const Sensors_Generic& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.Sensors.Generic)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.data() != 0) {
    _internal_set_data(from._internal_data());
  }
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
}

void Sensors_Generic::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.Sensors.Generic)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sensors_Generic::CopyFrom(const Sensors_Generic& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.Sensors.Generic)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sensors_Generic::IsInitialized() const {
  return true;
}

void Sensors_Generic::InternalSwap(Sensors_Generic* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sensors_Generic, id_)
      + sizeof(Sensors_Generic::id_)
      - PROTOBUF_FIELD_OFFSET(Sensors_Generic, data_)>(
          reinterpret_cast<char*>(&data_),
          reinterpret_cast<char*>(&other->data_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Sensors_Generic::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Sensors_Path::InitAsDefaultInstance() {
}
class Sensors_Path::_Internal {
 public:
};

void Sensors_Path::clear_waypoints() {
  waypoints_.Clear();
}
Sensors_Path::Sensors_Path(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  waypoints_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.Sensors.Path)
}
Sensors_Path::Sensors_Path(const Sensors_Path& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      waypoints_(from.waypoints_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Polaris.Sensors.Path)
}

void Sensors_Path::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Sensors_Path_sensors_2eproto.base);
}

Sensors_Path::~Sensors_Path() {
  // @@protoc_insertion_point(destructor:Polaris.Sensors.Path)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Sensors_Path::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Sensors_Path::ArenaDtor(void* object) {
  Sensors_Path* _this = reinterpret_cast< Sensors_Path* >(object);
  (void)_this;
}
void Sensors_Path::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Sensors_Path::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Sensors_Path& Sensors_Path::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Sensors_Path_sensors_2eproto.base);
  return *internal_default_instance();
}


void Sensors_Path::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.Sensors.Path)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  waypoints_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sensors_Path::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .Polaris.Waypoint waypoints = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_waypoints(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Sensors_Path::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.Sensors.Path)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Polaris.Waypoint waypoints = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_waypoints_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_waypoints(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.Sensors.Path)
  return target;
}

size_t Sensors_Path::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.Sensors.Path)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Polaris.Waypoint waypoints = 1;
  total_size += 1UL * this->_internal_waypoints_size();
  for (const auto& msg : this->waypoints_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Sensors_Path::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.Sensors.Path)
  GOOGLE_DCHECK_NE(&from, this);
  const Sensors_Path* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Sensors_Path>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.Sensors.Path)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.Sensors.Path)
    MergeFrom(*source);
  }
}

void Sensors_Path::MergeFrom(const Sensors_Path& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.Sensors.Path)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  waypoints_.MergeFrom(from.waypoints_);
}

void Sensors_Path::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.Sensors.Path)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sensors_Path::CopyFrom(const Sensors_Path& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.Sensors.Path)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sensors_Path::IsInitialized() const {
  return true;
}

void Sensors_Path::InternalSwap(Sensors_Path* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  waypoints_.InternalSwap(&other->waypoints_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Sensors_Path::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Sensors::InitAsDefaultInstance() {
  ::Polaris::_Sensors_default_instance_._instance.get_mutable()->gps_ = const_cast< ::Polaris::Sensors_Gps*>(
      ::Polaris::Sensors_Gps::internal_default_instance());
  ::Polaris::_Sensors_default_instance_._instance.get_mutable()->local_path_data_ = const_cast< ::Polaris::Sensors_Path*>(
      ::Polaris::Sensors_Path::internal_default_instance());
}
class Sensors::_Internal {
 public:
  static const ::Polaris::Sensors_Gps& gps(const Sensors* msg);
  static const ::Polaris::Sensors_Path& local_path_data(const Sensors* msg);
};

const ::Polaris::Sensors_Gps&
Sensors::_Internal::gps(const Sensors* msg) {
  return *msg->gps_;
}
const ::Polaris::Sensors_Path&
Sensors::_Internal::local_path_data(const Sensors* msg) {
  return *msg->local_path_data_;
}
Sensors::Sensors(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  wind_sensors_(arena),
  batteries_(arena),
  ais_ships_(arena),
  temp_sensors_(arena),
  ph_sensors_(arena),
  salinity_sensors_(arena),
  pressure_sensors_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Polaris.Sensors)
}
Sensors::Sensors(const Sensors& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      wind_sensors_(from.wind_sensors_),
      batteries_(from.batteries_),
      ais_ships_(from.ais_ships_),
      temp_sensors_(from.temp_sensors_),
      ph_sensors_(from.ph_sensors_),
      salinity_sensors_(from.salinity_sensors_),
      pressure_sensors_(from.pressure_sensors_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_gps()) {
    gps_ = new ::Polaris::Sensors_Gps(*from.gps_);
  } else {
    gps_ = nullptr;
  }
  if (from._internal_has_local_path_data()) {
    local_path_data_ = new ::Polaris::Sensors_Path(*from.local_path_data_);
  } else {
    local_path_data_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:Polaris.Sensors)
}

void Sensors::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Sensors_sensors_2eproto.base);
  ::memset(&gps_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&local_path_data_) -
      reinterpret_cast<char*>(&gps_)) + sizeof(local_path_data_));
}

Sensors::~Sensors() {
  // @@protoc_insertion_point(destructor:Polaris.Sensors)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Sensors::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete gps_;
  if (this != internal_default_instance()) delete local_path_data_;
}

void Sensors::ArenaDtor(void* object) {
  Sensors* _this = reinterpret_cast< Sensors* >(object);
  (void)_this;
}
void Sensors::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Sensors::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Sensors& Sensors::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Sensors_sensors_2eproto.base);
  return *internal_default_instance();
}


void Sensors::Clear() {
// @@protoc_insertion_point(message_clear_start:Polaris.Sensors)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  wind_sensors_.Clear();
  batteries_.Clear();
  ais_ships_.Clear();
  temp_sensors_.Clear();
  ph_sensors_.Clear();
  salinity_sensors_.Clear();
  pressure_sensors_.Clear();
  if (GetArena() == nullptr && gps_ != nullptr) {
    delete gps_;
  }
  gps_ = nullptr;
  if (GetArena() == nullptr && local_path_data_ != nullptr) {
    delete local_path_data_;
  }
  local_path_data_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Sensors::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .Polaris.Sensors.Gps gps = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_gps(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .Polaris.Sensors.Wind wind_sensors = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_wind_sensors(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .Polaris.Sensors.Battery batteries = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_batteries(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .Polaris.Sensors.Ais ais_ships = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ais_ships(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated float temp_sensors = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_temp_sensors(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45) {
          _internal_add_temp_sensors(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float ph_sensors = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_ph_sensors(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53) {
          _internal_add_ph_sensors(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float salinity_sensors = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_salinity_sensors(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61) {
          _internal_add_salinity_sensors(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float pressure_sensors = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_pressure_sensors(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69) {
          _internal_add_pressure_sensors(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // .Polaris.Sensors.Path local_path_data = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_local_path_data(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Sensors::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Polaris.Sensors)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Polaris.Sensors.Gps gps = 1;
  if (this->has_gps()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::gps(this), target, stream);
  }

  // repeated .Polaris.Sensors.Wind wind_sensors = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_wind_sensors_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_wind_sensors(i), target, stream);
  }

  // repeated .Polaris.Sensors.Battery batteries = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_batteries_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_batteries(i), target, stream);
  }

  // repeated .Polaris.Sensors.Ais ais_ships = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_ais_ships_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_ais_ships(i), target, stream);
  }

  // repeated float temp_sensors = 5;
  if (this->_internal_temp_sensors_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_temp_sensors(), target);
  }

  // repeated float ph_sensors = 6;
  if (this->_internal_ph_sensors_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_ph_sensors(), target);
  }

  // repeated float salinity_sensors = 7;
  if (this->_internal_salinity_sensors_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_salinity_sensors(), target);
  }

  // repeated float pressure_sensors = 8;
  if (this->_internal_pressure_sensors_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_pressure_sensors(), target);
  }

  // .Polaris.Sensors.Path local_path_data = 9;
  if (this->has_local_path_data()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        9, _Internal::local_path_data(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Polaris.Sensors)
  return target;
}

size_t Sensors::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Polaris.Sensors)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Polaris.Sensors.Wind wind_sensors = 2;
  total_size += 1UL * this->_internal_wind_sensors_size();
  for (const auto& msg : this->wind_sensors_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Polaris.Sensors.Battery batteries = 3;
  total_size += 1UL * this->_internal_batteries_size();
  for (const auto& msg : this->batteries_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .Polaris.Sensors.Ais ais_ships = 4;
  total_size += 1UL * this->_internal_ais_ships_size();
  for (const auto& msg : this->ais_ships_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated float temp_sensors = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_temp_sensors_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _temp_sensors_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float ph_sensors = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_ph_sensors_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _ph_sensors_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float salinity_sensors = 7;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_salinity_sensors_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _salinity_sensors_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float pressure_sensors = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_pressure_sensors_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _pressure_sensors_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .Polaris.Sensors.Gps gps = 1;
  if (this->has_gps()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *gps_);
  }

  // .Polaris.Sensors.Path local_path_data = 9;
  if (this->has_local_path_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *local_path_data_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Sensors::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Polaris.Sensors)
  GOOGLE_DCHECK_NE(&from, this);
  const Sensors* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Sensors>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Polaris.Sensors)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Polaris.Sensors)
    MergeFrom(*source);
  }
}

void Sensors::MergeFrom(const Sensors& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Polaris.Sensors)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  wind_sensors_.MergeFrom(from.wind_sensors_);
  batteries_.MergeFrom(from.batteries_);
  ais_ships_.MergeFrom(from.ais_ships_);
  temp_sensors_.MergeFrom(from.temp_sensors_);
  ph_sensors_.MergeFrom(from.ph_sensors_);
  salinity_sensors_.MergeFrom(from.salinity_sensors_);
  pressure_sensors_.MergeFrom(from.pressure_sensors_);
  if (from.has_gps()) {
    _internal_mutable_gps()->::Polaris::Sensors_Gps::MergeFrom(from._internal_gps());
  }
  if (from.has_local_path_data()) {
    _internal_mutable_local_path_data()->::Polaris::Sensors_Path::MergeFrom(from._internal_local_path_data());
  }
}

void Sensors::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Polaris.Sensors)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Sensors::CopyFrom(const Sensors& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Polaris.Sensors)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Sensors::IsInitialized() const {
  return true;
}

void Sensors::InternalSwap(Sensors* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  wind_sensors_.InternalSwap(&other->wind_sensors_);
  batteries_.InternalSwap(&other->batteries_);
  ais_ships_.InternalSwap(&other->ais_ships_);
  temp_sensors_.InternalSwap(&other->temp_sensors_);
  ph_sensors_.InternalSwap(&other->ph_sensors_);
  salinity_sensors_.InternalSwap(&other->salinity_sensors_);
  pressure_sensors_.InternalSwap(&other->pressure_sensors_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Sensors, local_path_data_)
      + sizeof(Sensors::local_path_data_)
      - PROTOBUF_FIELD_OFFSET(Sensors, gps_)>(
          reinterpret_cast<char*>(&gps_),
          reinterpret_cast<char*>(&other->gps_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Sensors::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Polaris
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Polaris::Sensors_Gps* Arena::CreateMaybeMessage< ::Polaris::Sensors_Gps >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::Sensors_Gps >(arena);
}
template<> PROTOBUF_NOINLINE ::Polaris::Sensors_Wind* Arena::CreateMaybeMessage< ::Polaris::Sensors_Wind >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::Sensors_Wind >(arena);
}
template<> PROTOBUF_NOINLINE ::Polaris::Sensors_Battery* Arena::CreateMaybeMessage< ::Polaris::Sensors_Battery >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::Sensors_Battery >(arena);
}
template<> PROTOBUF_NOINLINE ::Polaris::Sensors_Ais* Arena::CreateMaybeMessage< ::Polaris::Sensors_Ais >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::Sensors_Ais >(arena);
}
template<> PROTOBUF_NOINLINE ::Polaris::Sensors_Generic* Arena::CreateMaybeMessage< ::Polaris::Sensors_Generic >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::Sensors_Generic >(arena);
}
template<> PROTOBUF_NOINLINE ::Polaris::Sensors_Path* Arena::CreateMaybeMessage< ::Polaris::Sensors_Path >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::Sensors_Path >(arena);
}
template<> PROTOBUF_NOINLINE ::Polaris::Sensors* Arena::CreateMaybeMessage< ::Polaris::Sensors >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Polaris::Sensors >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
