// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global_path.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_global_5fpath_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_global_5fpath_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "waypoint.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_global_5fpath_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_global_5fpath_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_global_5fpath_2eproto;
namespace Polaris {
class GlobalPath;
class GlobalPathDefaultTypeInternal;
extern GlobalPathDefaultTypeInternal _GlobalPath_default_instance_;
}  // namespace Polaris
PROTOBUF_NAMESPACE_OPEN
template<> ::Polaris::GlobalPath* Arena::CreateMaybeMessage<::Polaris::GlobalPath>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Polaris {

// ===================================================================

class GlobalPath PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.GlobalPath) */ {
 public:
  inline GlobalPath() : GlobalPath(nullptr) {};
  virtual ~GlobalPath();

  GlobalPath(const GlobalPath& from);
  GlobalPath(GlobalPath&& from) noexcept
    : GlobalPath() {
    *this = ::std::move(from);
  }

  inline GlobalPath& operator=(const GlobalPath& from) {
    CopyFrom(from);
    return *this;
  }
  inline GlobalPath& operator=(GlobalPath&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const GlobalPath& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GlobalPath* internal_default_instance() {
    return reinterpret_cast<const GlobalPath*>(
               &_GlobalPath_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GlobalPath& a, GlobalPath& b) {
    a.Swap(&b);
  }
  inline void Swap(GlobalPath* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GlobalPath* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline GlobalPath* New() const final {
    return CreateMaybeMessage<GlobalPath>(nullptr);
  }

  GlobalPath* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<GlobalPath>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const GlobalPath& from);
  void MergeFrom(const GlobalPath& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlobalPath* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.GlobalPath";
  }
  protected:
  explicit GlobalPath(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_global_5fpath_2eproto);
    return ::descriptor_table_global_5fpath_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWaypointsFieldNumber = 2,
    kNumWaypointsFieldNumber = 1,
  };
  // repeated .Polaris.Waypoint waypoints = 2;
  int waypoints_size() const;
  private:
  int _internal_waypoints_size() const;
  public:
  void clear_waypoints();
  ::Polaris::Waypoint* mutable_waypoints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >*
      mutable_waypoints();
  private:
  const ::Polaris::Waypoint& _internal_waypoints(int index) const;
  ::Polaris::Waypoint* _internal_add_waypoints();
  public:
  const ::Polaris::Waypoint& waypoints(int index) const;
  ::Polaris::Waypoint* add_waypoints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >&
      waypoints() const;

  // uint32 num_waypoints = 1;
  void clear_num_waypoints();
  ::PROTOBUF_NAMESPACE_ID::uint32 num_waypoints() const;
  void set_num_waypoints(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_num_waypoints() const;
  void _internal_set_num_waypoints(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Polaris.GlobalPath)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint > waypoints_;
  ::PROTOBUF_NAMESPACE_ID::uint32 num_waypoints_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_global_5fpath_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GlobalPath

// uint32 num_waypoints = 1;
inline void GlobalPath::clear_num_waypoints() {
  num_waypoints_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GlobalPath::_internal_num_waypoints() const {
  return num_waypoints_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 GlobalPath::num_waypoints() const {
  // @@protoc_insertion_point(field_get:Polaris.GlobalPath.num_waypoints)
  return _internal_num_waypoints();
}
inline void GlobalPath::_internal_set_num_waypoints(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  num_waypoints_ = value;
}
inline void GlobalPath::set_num_waypoints(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_num_waypoints(value);
  // @@protoc_insertion_point(field_set:Polaris.GlobalPath.num_waypoints)
}

// repeated .Polaris.Waypoint waypoints = 2;
inline int GlobalPath::_internal_waypoints_size() const {
  return waypoints_.size();
}
inline int GlobalPath::waypoints_size() const {
  return _internal_waypoints_size();
}
inline ::Polaris::Waypoint* GlobalPath::mutable_waypoints(int index) {
  // @@protoc_insertion_point(field_mutable:Polaris.GlobalPath.waypoints)
  return waypoints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >*
GlobalPath::mutable_waypoints() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.GlobalPath.waypoints)
  return &waypoints_;
}
inline const ::Polaris::Waypoint& GlobalPath::_internal_waypoints(int index) const {
  return waypoints_.Get(index);
}
inline const ::Polaris::Waypoint& GlobalPath::waypoints(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.GlobalPath.waypoints)
  return _internal_waypoints(index);
}
inline ::Polaris::Waypoint* GlobalPath::_internal_add_waypoints() {
  return waypoints_.Add();
}
inline ::Polaris::Waypoint* GlobalPath::add_waypoints() {
  // @@protoc_insertion_point(field_add:Polaris.GlobalPath.waypoints)
  return _internal_add_waypoints();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >&
GlobalPath::waypoints() const {
  // @@protoc_insertion_point(field_list:Polaris.GlobalPath.waypoints)
  return waypoints_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Polaris

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_global_5fpath_2eproto
