// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sensors.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sensors_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sensors_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "waypoint.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sensors_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sensors_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sensors_2eproto;
namespace Polaris {
class Sensors;
class SensorsDefaultTypeInternal;
extern SensorsDefaultTypeInternal _Sensors_default_instance_;
class Sensors_Ais;
class Sensors_AisDefaultTypeInternal;
extern Sensors_AisDefaultTypeInternal _Sensors_Ais_default_instance_;
class Sensors_Battery;
class Sensors_BatteryDefaultTypeInternal;
extern Sensors_BatteryDefaultTypeInternal _Sensors_Battery_default_instance_;
class Sensors_Generic;
class Sensors_GenericDefaultTypeInternal;
extern Sensors_GenericDefaultTypeInternal _Sensors_Generic_default_instance_;
class Sensors_Gps;
class Sensors_GpsDefaultTypeInternal;
extern Sensors_GpsDefaultTypeInternal _Sensors_Gps_default_instance_;
class Sensors_Path;
class Sensors_PathDefaultTypeInternal;
extern Sensors_PathDefaultTypeInternal _Sensors_Path_default_instance_;
class Sensors_Wind;
class Sensors_WindDefaultTypeInternal;
extern Sensors_WindDefaultTypeInternal _Sensors_Wind_default_instance_;
}  // namespace Polaris
PROTOBUF_NAMESPACE_OPEN
template<> ::Polaris::Sensors* Arena::CreateMaybeMessage<::Polaris::Sensors>(Arena*);
template<> ::Polaris::Sensors_Ais* Arena::CreateMaybeMessage<::Polaris::Sensors_Ais>(Arena*);
template<> ::Polaris::Sensors_Battery* Arena::CreateMaybeMessage<::Polaris::Sensors_Battery>(Arena*);
template<> ::Polaris::Sensors_Generic* Arena::CreateMaybeMessage<::Polaris::Sensors_Generic>(Arena*);
template<> ::Polaris::Sensors_Gps* Arena::CreateMaybeMessage<::Polaris::Sensors_Gps>(Arena*);
template<> ::Polaris::Sensors_Path* Arena::CreateMaybeMessage<::Polaris::Sensors_Path>(Arena*);
template<> ::Polaris::Sensors_Wind* Arena::CreateMaybeMessage<::Polaris::Sensors_Wind>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Polaris {

// ===================================================================

class Sensors_Gps PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.Sensors.Gps) */ {
 public:
  inline Sensors_Gps() : Sensors_Gps(nullptr) {};
  virtual ~Sensors_Gps();

  Sensors_Gps(const Sensors_Gps& from);
  Sensors_Gps(Sensors_Gps&& from) noexcept
    : Sensors_Gps() {
    *this = ::std::move(from);
  }

  inline Sensors_Gps& operator=(const Sensors_Gps& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors_Gps& operator=(Sensors_Gps&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors_Gps& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sensors_Gps* internal_default_instance() {
    return reinterpret_cast<const Sensors_Gps*>(
               &_Sensors_Gps_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Sensors_Gps& a, Sensors_Gps& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors_Gps* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors_Gps* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors_Gps* New() const final {
    return CreateMaybeMessage<Sensors_Gps>(nullptr);
  }

  Sensors_Gps* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors_Gps>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors_Gps& from);
  void MergeFrom(const Sensors_Gps& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors_Gps* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.Sensors.Gps";
  }
  protected:
  explicit Sensors_Gps(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensors_2eproto);
    return ::descriptor_table_sensors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLatitudeFieldNumber = 1,
    kLongitudeFieldNumber = 2,
    kSpeedFieldNumber = 3,
    kHeadingFieldNumber = 4,
  };
  // float latitude = 1;
  void clear_latitude();
  float latitude() const;
  void set_latitude(float value);
  private:
  float _internal_latitude() const;
  void _internal_set_latitude(float value);
  public:

  // float longitude = 2;
  void clear_longitude();
  float longitude() const;
  void set_longitude(float value);
  private:
  float _internal_longitude() const;
  void _internal_set_longitude(float value);
  public:

  // float speed = 3;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // float heading = 4;
  void clear_heading();
  float heading() const;
  void set_heading(float value);
  private:
  float _internal_heading() const;
  void _internal_set_heading(float value);
  public:

  // @@protoc_insertion_point(class_scope:Polaris.Sensors.Gps)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float latitude_;
  float longitude_;
  float speed_;
  float heading_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensors_2eproto;
};
// -------------------------------------------------------------------

class Sensors_Wind PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.Sensors.Wind) */ {
 public:
  inline Sensors_Wind() : Sensors_Wind(nullptr) {};
  virtual ~Sensors_Wind();

  Sensors_Wind(const Sensors_Wind& from);
  Sensors_Wind(Sensors_Wind&& from) noexcept
    : Sensors_Wind() {
    *this = ::std::move(from);
  }

  inline Sensors_Wind& operator=(const Sensors_Wind& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors_Wind& operator=(Sensors_Wind&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors_Wind& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sensors_Wind* internal_default_instance() {
    return reinterpret_cast<const Sensors_Wind*>(
               &_Sensors_Wind_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Sensors_Wind& a, Sensors_Wind& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors_Wind* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors_Wind* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors_Wind* New() const final {
    return CreateMaybeMessage<Sensors_Wind>(nullptr);
  }

  Sensors_Wind* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors_Wind>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors_Wind& from);
  void MergeFrom(const Sensors_Wind& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors_Wind* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.Sensors.Wind";
  }
  protected:
  explicit Sensors_Wind(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensors_2eproto);
    return ::descriptor_table_sensors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSpeedFieldNumber = 1,
    kDirectionFieldNumber = 2,
  };
  // float speed = 1;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // int32 direction = 2;
  void clear_direction();
  ::PROTOBUF_NAMESPACE_ID::int32 direction() const;
  void set_direction(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_direction() const;
  void _internal_set_direction(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Polaris.Sensors.Wind)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float speed_;
  ::PROTOBUF_NAMESPACE_ID::int32 direction_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensors_2eproto;
};
// -------------------------------------------------------------------

class Sensors_Battery PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.Sensors.Battery) */ {
 public:
  inline Sensors_Battery() : Sensors_Battery(nullptr) {};
  virtual ~Sensors_Battery();

  Sensors_Battery(const Sensors_Battery& from);
  Sensors_Battery(Sensors_Battery&& from) noexcept
    : Sensors_Battery() {
    *this = ::std::move(from);
  }

  inline Sensors_Battery& operator=(const Sensors_Battery& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors_Battery& operator=(Sensors_Battery&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors_Battery& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sensors_Battery* internal_default_instance() {
    return reinterpret_cast<const Sensors_Battery*>(
               &_Sensors_Battery_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Sensors_Battery& a, Sensors_Battery& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors_Battery* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors_Battery* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors_Battery* New() const final {
    return CreateMaybeMessage<Sensors_Battery>(nullptr);
  }

  Sensors_Battery* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors_Battery>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors_Battery& from);
  void MergeFrom(const Sensors_Battery& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors_Battery* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.Sensors.Battery";
  }
  protected:
  explicit Sensors_Battery(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensors_2eproto);
    return ::descriptor_table_sensors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVoltageFieldNumber = 1,
    kCurrentFieldNumber = 2,
  };
  // float voltage = 1;
  void clear_voltage();
  float voltage() const;
  void set_voltage(float value);
  private:
  float _internal_voltage() const;
  void _internal_set_voltage(float value);
  public:

  // float current = 2;
  void clear_current();
  float current() const;
  void set_current(float value);
  private:
  float _internal_current() const;
  void _internal_set_current(float value);
  public:

  // @@protoc_insertion_point(class_scope:Polaris.Sensors.Battery)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float voltage_;
  float current_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensors_2eproto;
};
// -------------------------------------------------------------------

class Sensors_Ais PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.Sensors.Ais) */ {
 public:
  inline Sensors_Ais() : Sensors_Ais(nullptr) {};
  virtual ~Sensors_Ais();

  Sensors_Ais(const Sensors_Ais& from);
  Sensors_Ais(Sensors_Ais&& from) noexcept
    : Sensors_Ais() {
    *this = ::std::move(from);
  }

  inline Sensors_Ais& operator=(const Sensors_Ais& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors_Ais& operator=(Sensors_Ais&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors_Ais& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sensors_Ais* internal_default_instance() {
    return reinterpret_cast<const Sensors_Ais*>(
               &_Sensors_Ais_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Sensors_Ais& a, Sensors_Ais& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors_Ais* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors_Ais* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors_Ais* New() const final {
    return CreateMaybeMessage<Sensors_Ais>(nullptr);
  }

  Sensors_Ais* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors_Ais>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors_Ais& from);
  void MergeFrom(const Sensors_Ais& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors_Ais* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.Sensors.Ais";
  }
  protected:
  explicit Sensors_Ais(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensors_2eproto);
    return ::descriptor_table_sensors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kLatitudeFieldNumber = 2,
    kLongitudeFieldNumber = 3,
    kSogFieldNumber = 4,
    kCogFieldNumber = 5,
    kRotFieldNumber = 6,
    kWidthFieldNumber = 7,
    kLengthFieldNumber = 8,
  };
  // uint32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float latitude = 2;
  void clear_latitude();
  float latitude() const;
  void set_latitude(float value);
  private:
  float _internal_latitude() const;
  void _internal_set_latitude(float value);
  public:

  // float longitude = 3;
  void clear_longitude();
  float longitude() const;
  void set_longitude(float value);
  private:
  float _internal_longitude() const;
  void _internal_set_longitude(float value);
  public:

  // float sog = 4;
  void clear_sog();
  float sog() const;
  void set_sog(float value);
  private:
  float _internal_sog() const;
  void _internal_set_sog(float value);
  public:

  // float cog = 5;
  void clear_cog();
  float cog() const;
  void set_cog(float value);
  private:
  float _internal_cog() const;
  void _internal_set_cog(float value);
  public:

  // float rot = 6;
  void clear_rot();
  float rot() const;
  void set_rot(float value);
  private:
  float _internal_rot() const;
  void _internal_set_rot(float value);
  public:

  // float width = 7;
  void clear_width();
  float width() const;
  void set_width(float value);
  private:
  float _internal_width() const;
  void _internal_set_width(float value);
  public:

  // float length = 8;
  void clear_length();
  float length() const;
  void set_length(float value);
  private:
  float _internal_length() const;
  void _internal_set_length(float value);
  public:

  // @@protoc_insertion_point(class_scope:Polaris.Sensors.Ais)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  float latitude_;
  float longitude_;
  float sog_;
  float cog_;
  float rot_;
  float width_;
  float length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensors_2eproto;
};
// -------------------------------------------------------------------

class Sensors_Generic PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.Sensors.Generic) */ {
 public:
  inline Sensors_Generic() : Sensors_Generic(nullptr) {};
  virtual ~Sensors_Generic();

  Sensors_Generic(const Sensors_Generic& from);
  Sensors_Generic(Sensors_Generic&& from) noexcept
    : Sensors_Generic() {
    *this = ::std::move(from);
  }

  inline Sensors_Generic& operator=(const Sensors_Generic& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors_Generic& operator=(Sensors_Generic&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors_Generic& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sensors_Generic* internal_default_instance() {
    return reinterpret_cast<const Sensors_Generic*>(
               &_Sensors_Generic_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Sensors_Generic& a, Sensors_Generic& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors_Generic* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors_Generic* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors_Generic* New() const final {
    return CreateMaybeMessage<Sensors_Generic>(nullptr);
  }

  Sensors_Generic* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors_Generic>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors_Generic& from);
  void MergeFrom(const Sensors_Generic& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors_Generic* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.Sensors.Generic";
  }
  protected:
  explicit Sensors_Generic(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensors_2eproto);
    return ::descriptor_table_sensors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // uint64 data = 2;
  void clear_data();
  ::PROTOBUF_NAMESPACE_ID::uint64 data() const;
  void set_data(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_data() const;
  void _internal_set_data(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Polaris.Sensors.Generic)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 data_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensors_2eproto;
};
// -------------------------------------------------------------------

class Sensors_Path PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.Sensors.Path) */ {
 public:
  inline Sensors_Path() : Sensors_Path(nullptr) {};
  virtual ~Sensors_Path();

  Sensors_Path(const Sensors_Path& from);
  Sensors_Path(Sensors_Path&& from) noexcept
    : Sensors_Path() {
    *this = ::std::move(from);
  }

  inline Sensors_Path& operator=(const Sensors_Path& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors_Path& operator=(Sensors_Path&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors_Path& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sensors_Path* internal_default_instance() {
    return reinterpret_cast<const Sensors_Path*>(
               &_Sensors_Path_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Sensors_Path& a, Sensors_Path& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors_Path* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors_Path* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors_Path* New() const final {
    return CreateMaybeMessage<Sensors_Path>(nullptr);
  }

  Sensors_Path* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors_Path>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors_Path& from);
  void MergeFrom(const Sensors_Path& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors_Path* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.Sensors.Path";
  }
  protected:
  explicit Sensors_Path(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensors_2eproto);
    return ::descriptor_table_sensors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWaypointsFieldNumber = 1,
  };
  // repeated .Polaris.Waypoint waypoints = 1;
  int waypoints_size() const;
  private:
  int _internal_waypoints_size() const;
  public:
  void clear_waypoints();
  ::Polaris::Waypoint* mutable_waypoints(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >*
      mutable_waypoints();
  private:
  const ::Polaris::Waypoint& _internal_waypoints(int index) const;
  ::Polaris::Waypoint* _internal_add_waypoints();
  public:
  const ::Polaris::Waypoint& waypoints(int index) const;
  ::Polaris::Waypoint* add_waypoints();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >&
      waypoints() const;

  // @@protoc_insertion_point(class_scope:Polaris.Sensors.Path)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint > waypoints_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensors_2eproto;
};
// -------------------------------------------------------------------

class Sensors PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Polaris.Sensors) */ {
 public:
  inline Sensors() : Sensors(nullptr) {};
  virtual ~Sensors();

  Sensors(const Sensors& from);
  Sensors(Sensors&& from) noexcept
    : Sensors() {
    *this = ::std::move(from);
  }

  inline Sensors& operator=(const Sensors& from) {
    CopyFrom(from);
    return *this;
  }
  inline Sensors& operator=(Sensors&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Sensors& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sensors* internal_default_instance() {
    return reinterpret_cast<const Sensors*>(
               &_Sensors_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Sensors& a, Sensors& b) {
    a.Swap(&b);
  }
  inline void Swap(Sensors* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Sensors* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Sensors* New() const final {
    return CreateMaybeMessage<Sensors>(nullptr);
  }

  Sensors* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Sensors>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Sensors& from);
  void MergeFrom(const Sensors& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sensors* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Polaris.Sensors";
  }
  protected:
  explicit Sensors(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sensors_2eproto);
    return ::descriptor_table_sensors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Sensors_Gps Gps;
  typedef Sensors_Wind Wind;
  typedef Sensors_Battery Battery;
  typedef Sensors_Ais Ais;
  typedef Sensors_Generic Generic;
  typedef Sensors_Path Path;

  // accessors -------------------------------------------------------

  enum : int {
    kWindSensorsFieldNumber = 2,
    kBatteriesFieldNumber = 3,
    kAisShipsFieldNumber = 4,
    kTempSensorsFieldNumber = 5,
    kPhSensorsFieldNumber = 6,
    kSalinitySensorsFieldNumber = 7,
    kPressureSensorsFieldNumber = 8,
    kGpsFieldNumber = 1,
    kLocalPathDataFieldNumber = 9,
  };
  // repeated .Polaris.Sensors.Wind wind_sensors = 2;
  int wind_sensors_size() const;
  private:
  int _internal_wind_sensors_size() const;
  public:
  void clear_wind_sensors();
  ::Polaris::Sensors_Wind* mutable_wind_sensors(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Wind >*
      mutable_wind_sensors();
  private:
  const ::Polaris::Sensors_Wind& _internal_wind_sensors(int index) const;
  ::Polaris::Sensors_Wind* _internal_add_wind_sensors();
  public:
  const ::Polaris::Sensors_Wind& wind_sensors(int index) const;
  ::Polaris::Sensors_Wind* add_wind_sensors();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Wind >&
      wind_sensors() const;

  // repeated .Polaris.Sensors.Battery batteries = 3;
  int batteries_size() const;
  private:
  int _internal_batteries_size() const;
  public:
  void clear_batteries();
  ::Polaris::Sensors_Battery* mutable_batteries(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Battery >*
      mutable_batteries();
  private:
  const ::Polaris::Sensors_Battery& _internal_batteries(int index) const;
  ::Polaris::Sensors_Battery* _internal_add_batteries();
  public:
  const ::Polaris::Sensors_Battery& batteries(int index) const;
  ::Polaris::Sensors_Battery* add_batteries();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Battery >&
      batteries() const;

  // repeated .Polaris.Sensors.Ais ais_ships = 4;
  int ais_ships_size() const;
  private:
  int _internal_ais_ships_size() const;
  public:
  void clear_ais_ships();
  ::Polaris::Sensors_Ais* mutable_ais_ships(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Ais >*
      mutable_ais_ships();
  private:
  const ::Polaris::Sensors_Ais& _internal_ais_ships(int index) const;
  ::Polaris::Sensors_Ais* _internal_add_ais_ships();
  public:
  const ::Polaris::Sensors_Ais& ais_ships(int index) const;
  ::Polaris::Sensors_Ais* add_ais_ships();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Ais >&
      ais_ships() const;

  // repeated float temp_sensors = 5;
  int temp_sensors_size() const;
  private:
  int _internal_temp_sensors_size() const;
  public:
  void clear_temp_sensors();
  private:
  float _internal_temp_sensors(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_temp_sensors() const;
  void _internal_add_temp_sensors(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_temp_sensors();
  public:
  float temp_sensors(int index) const;
  void set_temp_sensors(int index, float value);
  void add_temp_sensors(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      temp_sensors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_temp_sensors();

  // repeated float ph_sensors = 6;
  int ph_sensors_size() const;
  private:
  int _internal_ph_sensors_size() const;
  public:
  void clear_ph_sensors();
  private:
  float _internal_ph_sensors(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_ph_sensors() const;
  void _internal_add_ph_sensors(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_ph_sensors();
  public:
  float ph_sensors(int index) const;
  void set_ph_sensors(int index, float value);
  void add_ph_sensors(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      ph_sensors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_ph_sensors();

  // repeated float salinity_sensors = 7;
  int salinity_sensors_size() const;
  private:
  int _internal_salinity_sensors_size() const;
  public:
  void clear_salinity_sensors();
  private:
  float _internal_salinity_sensors(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_salinity_sensors() const;
  void _internal_add_salinity_sensors(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_salinity_sensors();
  public:
  float salinity_sensors(int index) const;
  void set_salinity_sensors(int index, float value);
  void add_salinity_sensors(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      salinity_sensors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_salinity_sensors();

  // repeated float pressure_sensors = 8;
  int pressure_sensors_size() const;
  private:
  int _internal_pressure_sensors_size() const;
  public:
  void clear_pressure_sensors();
  private:
  float _internal_pressure_sensors(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_pressure_sensors() const;
  void _internal_add_pressure_sensors(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_pressure_sensors();
  public:
  float pressure_sensors(int index) const;
  void set_pressure_sensors(int index, float value);
  void add_pressure_sensors(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      pressure_sensors() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_pressure_sensors();

  // .Polaris.Sensors.Gps gps = 1;
  bool has_gps() const;
  private:
  bool _internal_has_gps() const;
  public:
  void clear_gps();
  const ::Polaris::Sensors_Gps& gps() const;
  ::Polaris::Sensors_Gps* release_gps();
  ::Polaris::Sensors_Gps* mutable_gps();
  void set_allocated_gps(::Polaris::Sensors_Gps* gps);
  private:
  const ::Polaris::Sensors_Gps& _internal_gps() const;
  ::Polaris::Sensors_Gps* _internal_mutable_gps();
  public:
  void unsafe_arena_set_allocated_gps(
      ::Polaris::Sensors_Gps* gps);
  ::Polaris::Sensors_Gps* unsafe_arena_release_gps();

  // .Polaris.Sensors.Path local_path_data = 9;
  bool has_local_path_data() const;
  private:
  bool _internal_has_local_path_data() const;
  public:
  void clear_local_path_data();
  const ::Polaris::Sensors_Path& local_path_data() const;
  ::Polaris::Sensors_Path* release_local_path_data();
  ::Polaris::Sensors_Path* mutable_local_path_data();
  void set_allocated_local_path_data(::Polaris::Sensors_Path* local_path_data);
  private:
  const ::Polaris::Sensors_Path& _internal_local_path_data() const;
  ::Polaris::Sensors_Path* _internal_mutable_local_path_data();
  public:
  void unsafe_arena_set_allocated_local_path_data(
      ::Polaris::Sensors_Path* local_path_data);
  ::Polaris::Sensors_Path* unsafe_arena_release_local_path_data();

  // @@protoc_insertion_point(class_scope:Polaris.Sensors)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Wind > wind_sensors_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Battery > batteries_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Ais > ais_ships_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > temp_sensors_;
  mutable std::atomic<int> _temp_sensors_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > ph_sensors_;
  mutable std::atomic<int> _ph_sensors_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > salinity_sensors_;
  mutable std::atomic<int> _salinity_sensors_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > pressure_sensors_;
  mutable std::atomic<int> _pressure_sensors_cached_byte_size_;
  ::Polaris::Sensors_Gps* gps_;
  ::Polaris::Sensors_Path* local_path_data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sensors_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Sensors_Gps

// float latitude = 1;
inline void Sensors_Gps::clear_latitude() {
  latitude_ = 0;
}
inline float Sensors_Gps::_internal_latitude() const {
  return latitude_;
}
inline float Sensors_Gps::latitude() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Gps.latitude)
  return _internal_latitude();
}
inline void Sensors_Gps::_internal_set_latitude(float value) {
  
  latitude_ = value;
}
inline void Sensors_Gps::set_latitude(float value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Gps.latitude)
}

// float longitude = 2;
inline void Sensors_Gps::clear_longitude() {
  longitude_ = 0;
}
inline float Sensors_Gps::_internal_longitude() const {
  return longitude_;
}
inline float Sensors_Gps::longitude() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Gps.longitude)
  return _internal_longitude();
}
inline void Sensors_Gps::_internal_set_longitude(float value) {
  
  longitude_ = value;
}
inline void Sensors_Gps::set_longitude(float value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Gps.longitude)
}

// float speed = 3;
inline void Sensors_Gps::clear_speed() {
  speed_ = 0;
}
inline float Sensors_Gps::_internal_speed() const {
  return speed_;
}
inline float Sensors_Gps::speed() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Gps.speed)
  return _internal_speed();
}
inline void Sensors_Gps::_internal_set_speed(float value) {
  
  speed_ = value;
}
inline void Sensors_Gps::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Gps.speed)
}

// float heading = 4;
inline void Sensors_Gps::clear_heading() {
  heading_ = 0;
}
inline float Sensors_Gps::_internal_heading() const {
  return heading_;
}
inline float Sensors_Gps::heading() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Gps.heading)
  return _internal_heading();
}
inline void Sensors_Gps::_internal_set_heading(float value) {
  
  heading_ = value;
}
inline void Sensors_Gps::set_heading(float value) {
  _internal_set_heading(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Gps.heading)
}

// -------------------------------------------------------------------

// Sensors_Wind

// float speed = 1;
inline void Sensors_Wind::clear_speed() {
  speed_ = 0;
}
inline float Sensors_Wind::_internal_speed() const {
  return speed_;
}
inline float Sensors_Wind::speed() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Wind.speed)
  return _internal_speed();
}
inline void Sensors_Wind::_internal_set_speed(float value) {
  
  speed_ = value;
}
inline void Sensors_Wind::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Wind.speed)
}

// int32 direction = 2;
inline void Sensors_Wind::clear_direction() {
  direction_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Sensors_Wind::_internal_direction() const {
  return direction_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Sensors_Wind::direction() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Wind.direction)
  return _internal_direction();
}
inline void Sensors_Wind::_internal_set_direction(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  direction_ = value;
}
inline void Sensors_Wind::set_direction(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_direction(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Wind.direction)
}

// -------------------------------------------------------------------

// Sensors_Battery

// float voltage = 1;
inline void Sensors_Battery::clear_voltage() {
  voltage_ = 0;
}
inline float Sensors_Battery::_internal_voltage() const {
  return voltage_;
}
inline float Sensors_Battery::voltage() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Battery.voltage)
  return _internal_voltage();
}
inline void Sensors_Battery::_internal_set_voltage(float value) {
  
  voltage_ = value;
}
inline void Sensors_Battery::set_voltage(float value) {
  _internal_set_voltage(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Battery.voltage)
}

// float current = 2;
inline void Sensors_Battery::clear_current() {
  current_ = 0;
}
inline float Sensors_Battery::_internal_current() const {
  return current_;
}
inline float Sensors_Battery::current() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Battery.current)
  return _internal_current();
}
inline void Sensors_Battery::_internal_set_current(float value) {
  
  current_ = value;
}
inline void Sensors_Battery::set_current(float value) {
  _internal_set_current(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Battery.current)
}

// -------------------------------------------------------------------

// Sensors_Ais

// uint32 id = 1;
inline void Sensors_Ais::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Sensors_Ais::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Sensors_Ais::id() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.id)
  return _internal_id();
}
inline void Sensors_Ais::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
}
inline void Sensors_Ais::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.id)
}

// float latitude = 2;
inline void Sensors_Ais::clear_latitude() {
  latitude_ = 0;
}
inline float Sensors_Ais::_internal_latitude() const {
  return latitude_;
}
inline float Sensors_Ais::latitude() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.latitude)
  return _internal_latitude();
}
inline void Sensors_Ais::_internal_set_latitude(float value) {
  
  latitude_ = value;
}
inline void Sensors_Ais::set_latitude(float value) {
  _internal_set_latitude(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.latitude)
}

// float longitude = 3;
inline void Sensors_Ais::clear_longitude() {
  longitude_ = 0;
}
inline float Sensors_Ais::_internal_longitude() const {
  return longitude_;
}
inline float Sensors_Ais::longitude() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.longitude)
  return _internal_longitude();
}
inline void Sensors_Ais::_internal_set_longitude(float value) {
  
  longitude_ = value;
}
inline void Sensors_Ais::set_longitude(float value) {
  _internal_set_longitude(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.longitude)
}

// float sog = 4;
inline void Sensors_Ais::clear_sog() {
  sog_ = 0;
}
inline float Sensors_Ais::_internal_sog() const {
  return sog_;
}
inline float Sensors_Ais::sog() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.sog)
  return _internal_sog();
}
inline void Sensors_Ais::_internal_set_sog(float value) {
  
  sog_ = value;
}
inline void Sensors_Ais::set_sog(float value) {
  _internal_set_sog(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.sog)
}

// float cog = 5;
inline void Sensors_Ais::clear_cog() {
  cog_ = 0;
}
inline float Sensors_Ais::_internal_cog() const {
  return cog_;
}
inline float Sensors_Ais::cog() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.cog)
  return _internal_cog();
}
inline void Sensors_Ais::_internal_set_cog(float value) {
  
  cog_ = value;
}
inline void Sensors_Ais::set_cog(float value) {
  _internal_set_cog(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.cog)
}

// float rot = 6;
inline void Sensors_Ais::clear_rot() {
  rot_ = 0;
}
inline float Sensors_Ais::_internal_rot() const {
  return rot_;
}
inline float Sensors_Ais::rot() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.rot)
  return _internal_rot();
}
inline void Sensors_Ais::_internal_set_rot(float value) {
  
  rot_ = value;
}
inline void Sensors_Ais::set_rot(float value) {
  _internal_set_rot(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.rot)
}

// float width = 7;
inline void Sensors_Ais::clear_width() {
  width_ = 0;
}
inline float Sensors_Ais::_internal_width() const {
  return width_;
}
inline float Sensors_Ais::width() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.width)
  return _internal_width();
}
inline void Sensors_Ais::_internal_set_width(float value) {
  
  width_ = value;
}
inline void Sensors_Ais::set_width(float value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.width)
}

// float length = 8;
inline void Sensors_Ais::clear_length() {
  length_ = 0;
}
inline float Sensors_Ais::_internal_length() const {
  return length_;
}
inline float Sensors_Ais::length() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Ais.length)
  return _internal_length();
}
inline void Sensors_Ais::_internal_set_length(float value) {
  
  length_ = value;
}
inline void Sensors_Ais::set_length(float value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Ais.length)
}

// -------------------------------------------------------------------

// Sensors_Generic

// uint32 id = 1;
inline void Sensors_Generic::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Sensors_Generic::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Sensors_Generic::id() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Generic.id)
  return _internal_id();
}
inline void Sensors_Generic::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
}
inline void Sensors_Generic::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Generic.id)
}

// uint64 data = 2;
inline void Sensors_Generic::clear_data() {
  data_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Sensors_Generic::_internal_data() const {
  return data_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Sensors_Generic::data() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Generic.data)
  return _internal_data();
}
inline void Sensors_Generic::_internal_set_data(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  data_ = value;
}
inline void Sensors_Generic::set_data(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.Generic.data)
}

// -------------------------------------------------------------------

// Sensors_Path

// repeated .Polaris.Waypoint waypoints = 1;
inline int Sensors_Path::_internal_waypoints_size() const {
  return waypoints_.size();
}
inline int Sensors_Path::waypoints_size() const {
  return _internal_waypoints_size();
}
inline ::Polaris::Waypoint* Sensors_Path::mutable_waypoints(int index) {
  // @@protoc_insertion_point(field_mutable:Polaris.Sensors.Path.waypoints)
  return waypoints_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >*
Sensors_Path::mutable_waypoints() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.Path.waypoints)
  return &waypoints_;
}
inline const ::Polaris::Waypoint& Sensors_Path::_internal_waypoints(int index) const {
  return waypoints_.Get(index);
}
inline const ::Polaris::Waypoint& Sensors_Path::waypoints(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.Path.waypoints)
  return _internal_waypoints(index);
}
inline ::Polaris::Waypoint* Sensors_Path::_internal_add_waypoints() {
  return waypoints_.Add();
}
inline ::Polaris::Waypoint* Sensors_Path::add_waypoints() {
  // @@protoc_insertion_point(field_add:Polaris.Sensors.Path.waypoints)
  return _internal_add_waypoints();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Waypoint >&
Sensors_Path::waypoints() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.Path.waypoints)
  return waypoints_;
}

// -------------------------------------------------------------------

// Sensors

// .Polaris.Sensors.Gps gps = 1;
inline bool Sensors::_internal_has_gps() const {
  return this != internal_default_instance() && gps_ != nullptr;
}
inline bool Sensors::has_gps() const {
  return _internal_has_gps();
}
inline void Sensors::clear_gps() {
  if (GetArena() == nullptr && gps_ != nullptr) {
    delete gps_;
  }
  gps_ = nullptr;
}
inline const ::Polaris::Sensors_Gps& Sensors::_internal_gps() const {
  const ::Polaris::Sensors_Gps* p = gps_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Polaris::Sensors_Gps*>(
      &::Polaris::_Sensors_Gps_default_instance_);
}
inline const ::Polaris::Sensors_Gps& Sensors::gps() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.gps)
  return _internal_gps();
}
inline void Sensors::unsafe_arena_set_allocated_gps(
    ::Polaris::Sensors_Gps* gps) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(gps_);
  }
  gps_ = gps;
  if (gps) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Polaris.Sensors.gps)
}
inline ::Polaris::Sensors_Gps* Sensors::release_gps() {
  auto temp = unsafe_arena_release_gps();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Polaris::Sensors_Gps* Sensors::unsafe_arena_release_gps() {
  // @@protoc_insertion_point(field_release:Polaris.Sensors.gps)
  
  ::Polaris::Sensors_Gps* temp = gps_;
  gps_ = nullptr;
  return temp;
}
inline ::Polaris::Sensors_Gps* Sensors::_internal_mutable_gps() {
  
  if (gps_ == nullptr) {
    auto* p = CreateMaybeMessage<::Polaris::Sensors_Gps>(GetArena());
    gps_ = p;
  }
  return gps_;
}
inline ::Polaris::Sensors_Gps* Sensors::mutable_gps() {
  // @@protoc_insertion_point(field_mutable:Polaris.Sensors.gps)
  return _internal_mutable_gps();
}
inline void Sensors::set_allocated_gps(::Polaris::Sensors_Gps* gps) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete gps_;
  }
  if (gps) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(gps);
    if (message_arena != submessage_arena) {
      gps = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, gps, submessage_arena);
    }
    
  } else {
    
  }
  gps_ = gps;
  // @@protoc_insertion_point(field_set_allocated:Polaris.Sensors.gps)
}

// repeated .Polaris.Sensors.Wind wind_sensors = 2;
inline int Sensors::_internal_wind_sensors_size() const {
  return wind_sensors_.size();
}
inline int Sensors::wind_sensors_size() const {
  return _internal_wind_sensors_size();
}
inline void Sensors::clear_wind_sensors() {
  wind_sensors_.Clear();
}
inline ::Polaris::Sensors_Wind* Sensors::mutable_wind_sensors(int index) {
  // @@protoc_insertion_point(field_mutable:Polaris.Sensors.wind_sensors)
  return wind_sensors_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Wind >*
Sensors::mutable_wind_sensors() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.wind_sensors)
  return &wind_sensors_;
}
inline const ::Polaris::Sensors_Wind& Sensors::_internal_wind_sensors(int index) const {
  return wind_sensors_.Get(index);
}
inline const ::Polaris::Sensors_Wind& Sensors::wind_sensors(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.wind_sensors)
  return _internal_wind_sensors(index);
}
inline ::Polaris::Sensors_Wind* Sensors::_internal_add_wind_sensors() {
  return wind_sensors_.Add();
}
inline ::Polaris::Sensors_Wind* Sensors::add_wind_sensors() {
  // @@protoc_insertion_point(field_add:Polaris.Sensors.wind_sensors)
  return _internal_add_wind_sensors();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Wind >&
Sensors::wind_sensors() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.wind_sensors)
  return wind_sensors_;
}

// repeated .Polaris.Sensors.Battery batteries = 3;
inline int Sensors::_internal_batteries_size() const {
  return batteries_.size();
}
inline int Sensors::batteries_size() const {
  return _internal_batteries_size();
}
inline void Sensors::clear_batteries() {
  batteries_.Clear();
}
inline ::Polaris::Sensors_Battery* Sensors::mutable_batteries(int index) {
  // @@protoc_insertion_point(field_mutable:Polaris.Sensors.batteries)
  return batteries_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Battery >*
Sensors::mutable_batteries() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.batteries)
  return &batteries_;
}
inline const ::Polaris::Sensors_Battery& Sensors::_internal_batteries(int index) const {
  return batteries_.Get(index);
}
inline const ::Polaris::Sensors_Battery& Sensors::batteries(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.batteries)
  return _internal_batteries(index);
}
inline ::Polaris::Sensors_Battery* Sensors::_internal_add_batteries() {
  return batteries_.Add();
}
inline ::Polaris::Sensors_Battery* Sensors::add_batteries() {
  // @@protoc_insertion_point(field_add:Polaris.Sensors.batteries)
  return _internal_add_batteries();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Battery >&
Sensors::batteries() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.batteries)
  return batteries_;
}

// repeated .Polaris.Sensors.Ais ais_ships = 4;
inline int Sensors::_internal_ais_ships_size() const {
  return ais_ships_.size();
}
inline int Sensors::ais_ships_size() const {
  return _internal_ais_ships_size();
}
inline void Sensors::clear_ais_ships() {
  ais_ships_.Clear();
}
inline ::Polaris::Sensors_Ais* Sensors::mutable_ais_ships(int index) {
  // @@protoc_insertion_point(field_mutable:Polaris.Sensors.ais_ships)
  return ais_ships_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Ais >*
Sensors::mutable_ais_ships() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.ais_ships)
  return &ais_ships_;
}
inline const ::Polaris::Sensors_Ais& Sensors::_internal_ais_ships(int index) const {
  return ais_ships_.Get(index);
}
inline const ::Polaris::Sensors_Ais& Sensors::ais_ships(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.ais_ships)
  return _internal_ais_ships(index);
}
inline ::Polaris::Sensors_Ais* Sensors::_internal_add_ais_ships() {
  return ais_ships_.Add();
}
inline ::Polaris::Sensors_Ais* Sensors::add_ais_ships() {
  // @@protoc_insertion_point(field_add:Polaris.Sensors.ais_ships)
  return _internal_add_ais_ships();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Polaris::Sensors_Ais >&
Sensors::ais_ships() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.ais_ships)
  return ais_ships_;
}

// repeated float temp_sensors = 5;
inline int Sensors::_internal_temp_sensors_size() const {
  return temp_sensors_.size();
}
inline int Sensors::temp_sensors_size() const {
  return _internal_temp_sensors_size();
}
inline void Sensors::clear_temp_sensors() {
  temp_sensors_.Clear();
}
inline float Sensors::_internal_temp_sensors(int index) const {
  return temp_sensors_.Get(index);
}
inline float Sensors::temp_sensors(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.temp_sensors)
  return _internal_temp_sensors(index);
}
inline void Sensors::set_temp_sensors(int index, float value) {
  temp_sensors_.Set(index, value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.temp_sensors)
}
inline void Sensors::_internal_add_temp_sensors(float value) {
  temp_sensors_.Add(value);
}
inline void Sensors::add_temp_sensors(float value) {
  _internal_add_temp_sensors(value);
  // @@protoc_insertion_point(field_add:Polaris.Sensors.temp_sensors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::_internal_temp_sensors() const {
  return temp_sensors_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::temp_sensors() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.temp_sensors)
  return _internal_temp_sensors();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::_internal_mutable_temp_sensors() {
  return &temp_sensors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::mutable_temp_sensors() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.temp_sensors)
  return _internal_mutable_temp_sensors();
}

// repeated float ph_sensors = 6;
inline int Sensors::_internal_ph_sensors_size() const {
  return ph_sensors_.size();
}
inline int Sensors::ph_sensors_size() const {
  return _internal_ph_sensors_size();
}
inline void Sensors::clear_ph_sensors() {
  ph_sensors_.Clear();
}
inline float Sensors::_internal_ph_sensors(int index) const {
  return ph_sensors_.Get(index);
}
inline float Sensors::ph_sensors(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.ph_sensors)
  return _internal_ph_sensors(index);
}
inline void Sensors::set_ph_sensors(int index, float value) {
  ph_sensors_.Set(index, value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.ph_sensors)
}
inline void Sensors::_internal_add_ph_sensors(float value) {
  ph_sensors_.Add(value);
}
inline void Sensors::add_ph_sensors(float value) {
  _internal_add_ph_sensors(value);
  // @@protoc_insertion_point(field_add:Polaris.Sensors.ph_sensors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::_internal_ph_sensors() const {
  return ph_sensors_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::ph_sensors() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.ph_sensors)
  return _internal_ph_sensors();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::_internal_mutable_ph_sensors() {
  return &ph_sensors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::mutable_ph_sensors() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.ph_sensors)
  return _internal_mutable_ph_sensors();
}

// repeated float salinity_sensors = 7;
inline int Sensors::_internal_salinity_sensors_size() const {
  return salinity_sensors_.size();
}
inline int Sensors::salinity_sensors_size() const {
  return _internal_salinity_sensors_size();
}
inline void Sensors::clear_salinity_sensors() {
  salinity_sensors_.Clear();
}
inline float Sensors::_internal_salinity_sensors(int index) const {
  return salinity_sensors_.Get(index);
}
inline float Sensors::salinity_sensors(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.salinity_sensors)
  return _internal_salinity_sensors(index);
}
inline void Sensors::set_salinity_sensors(int index, float value) {
  salinity_sensors_.Set(index, value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.salinity_sensors)
}
inline void Sensors::_internal_add_salinity_sensors(float value) {
  salinity_sensors_.Add(value);
}
inline void Sensors::add_salinity_sensors(float value) {
  _internal_add_salinity_sensors(value);
  // @@protoc_insertion_point(field_add:Polaris.Sensors.salinity_sensors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::_internal_salinity_sensors() const {
  return salinity_sensors_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::salinity_sensors() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.salinity_sensors)
  return _internal_salinity_sensors();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::_internal_mutable_salinity_sensors() {
  return &salinity_sensors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::mutable_salinity_sensors() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.salinity_sensors)
  return _internal_mutable_salinity_sensors();
}

// repeated float pressure_sensors = 8;
inline int Sensors::_internal_pressure_sensors_size() const {
  return pressure_sensors_.size();
}
inline int Sensors::pressure_sensors_size() const {
  return _internal_pressure_sensors_size();
}
inline void Sensors::clear_pressure_sensors() {
  pressure_sensors_.Clear();
}
inline float Sensors::_internal_pressure_sensors(int index) const {
  return pressure_sensors_.Get(index);
}
inline float Sensors::pressure_sensors(int index) const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.pressure_sensors)
  return _internal_pressure_sensors(index);
}
inline void Sensors::set_pressure_sensors(int index, float value) {
  pressure_sensors_.Set(index, value);
  // @@protoc_insertion_point(field_set:Polaris.Sensors.pressure_sensors)
}
inline void Sensors::_internal_add_pressure_sensors(float value) {
  pressure_sensors_.Add(value);
}
inline void Sensors::add_pressure_sensors(float value) {
  _internal_add_pressure_sensors(value);
  // @@protoc_insertion_point(field_add:Polaris.Sensors.pressure_sensors)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::_internal_pressure_sensors() const {
  return pressure_sensors_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Sensors::pressure_sensors() const {
  // @@protoc_insertion_point(field_list:Polaris.Sensors.pressure_sensors)
  return _internal_pressure_sensors();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::_internal_mutable_pressure_sensors() {
  return &pressure_sensors_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Sensors::mutable_pressure_sensors() {
  // @@protoc_insertion_point(field_mutable_list:Polaris.Sensors.pressure_sensors)
  return _internal_mutable_pressure_sensors();
}

// .Polaris.Sensors.Path local_path_data = 9;
inline bool Sensors::_internal_has_local_path_data() const {
  return this != internal_default_instance() && local_path_data_ != nullptr;
}
inline bool Sensors::has_local_path_data() const {
  return _internal_has_local_path_data();
}
inline void Sensors::clear_local_path_data() {
  if (GetArena() == nullptr && local_path_data_ != nullptr) {
    delete local_path_data_;
  }
  local_path_data_ = nullptr;
}
inline const ::Polaris::Sensors_Path& Sensors::_internal_local_path_data() const {
  const ::Polaris::Sensors_Path* p = local_path_data_;
  return p != nullptr ? *p : *reinterpret_cast<const ::Polaris::Sensors_Path*>(
      &::Polaris::_Sensors_Path_default_instance_);
}
inline const ::Polaris::Sensors_Path& Sensors::local_path_data() const {
  // @@protoc_insertion_point(field_get:Polaris.Sensors.local_path_data)
  return _internal_local_path_data();
}
inline void Sensors::unsafe_arena_set_allocated_local_path_data(
    ::Polaris::Sensors_Path* local_path_data) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(local_path_data_);
  }
  local_path_data_ = local_path_data;
  if (local_path_data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Polaris.Sensors.local_path_data)
}
inline ::Polaris::Sensors_Path* Sensors::release_local_path_data() {
  auto temp = unsafe_arena_release_local_path_data();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::Polaris::Sensors_Path* Sensors::unsafe_arena_release_local_path_data() {
  // @@protoc_insertion_point(field_release:Polaris.Sensors.local_path_data)
  
  ::Polaris::Sensors_Path* temp = local_path_data_;
  local_path_data_ = nullptr;
  return temp;
}
inline ::Polaris::Sensors_Path* Sensors::_internal_mutable_local_path_data() {
  
  if (local_path_data_ == nullptr) {
    auto* p = CreateMaybeMessage<::Polaris::Sensors_Path>(GetArena());
    local_path_data_ = p;
  }
  return local_path_data_;
}
inline ::Polaris::Sensors_Path* Sensors::mutable_local_path_data() {
  // @@protoc_insertion_point(field_mutable:Polaris.Sensors.local_path_data)
  return _internal_mutable_local_path_data();
}
inline void Sensors::set_allocated_local_path_data(::Polaris::Sensors_Path* local_path_data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete local_path_data_;
  }
  if (local_path_data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(local_path_data);
    if (message_arena != submessage_arena) {
      local_path_data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, local_path_data, submessage_arena);
    }
    
  } else {
    
  }
  local_path_data_ = local_path_data;
  // @@protoc_insertion_point(field_set_allocated:Polaris.Sensors.local_path_data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Polaris

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sensors_2eproto
