# Configuration that enables the mandatory production modules and uses their defaults
can_transceiver_node:
  ros__parameters:
    enabled: true

cached_fib_node:
  ros__parameters:
    enabled: false

local_transceiver_node:
  ros__parameters:
    enabled: true

mock_ais_node:
  ros__parameters:
    enabled: false

remote_transceiver_node:
  ros__parameters:
    enabled: true
