#!/usr/bin/env python3
"""Turns the raw SolidWorks CAD export into the meshes models/polaris ships.

The CAD export is unusable as-is for two independent reasons, both fixed here:

1. **It is in a z-down frame.** The SolidWorks assembly was built with z pointing
   down, and the URDF exporter carried that through untouched. Loaded as-is, the
   wingsail hangs ~3 m below the hull, the trim tab sits underwater, and the rudder
   points up into the air. Every mesh is therefore rotated 180 deg about x here.

2. **base_hull.STL is 1.35 M triangles / 67 MB.** The devcontainer forces software
   rendering (`LIBGL_ALWAYS_SOFTWARE=1`, no `/dev/dri`) on every platform, so that
   geometry is rasterised on the CPU everywhere and costs ~1 GB of extra RSS in the
   Gazebo GUI. Decimating to ~35 k triangles removes that without a visible change
   at the scale the boat is drawn.

The hull mesh is additionally translated so the model origin lands on the centre of
gravity, matching the convention models/polaris_basic uses and the one the
`*_CE_REL_TO_CG` constants in `boat_simulator/common/constants.py` are expressed
against. Child links are rotated only -- their origins are placed by the joint
offsets in model.sdf, which are listed in JOINT_ORIGINS_CG_FRAME below for reference.

Usage:
    pip install fast-simplification
    python3 tools/prepare_polaris_meshes.py

Reads models/polaris/meshes/raw/*.STL (gitignored, ~70 MB) and writes the decimated,
reframed meshes to models/polaris/meshes/*.STL, which are the ones committed.
"""

import os
import struct
import sys

import numpy as np

# Centre of gravity in the raw CAD frame, from the URDF's base_hull <inertial><origin>.
CG_CAD = np.array([0.079791, 0.00053586, 0.50523])

# 180 deg about x: converts the CAD z-down frame to Gazebo's z-up ENU convention.
FLIP = np.diag([1.0, -1.0, -1.0])

# Target triangle counts. The hull carries all the visual weight; the appendages are
# already cheap, and the two small foils are left untouched.
TARGETS = {
    "base_hull": 35000,
    "link_wingsail": 8000,
    "link_rudder": None,
    "link_trim_tab": None,
}

# Joint origins in the CG-centred, z-up frame, i.e. FLIP @ p_cad - FLIP @ CG_CAD.
# Printed by this script and transcribed into model.sdf; kept here so the two stay
# traceable to the CAD export rather than looking like hand-tuned numbers.
JOINT_ORIGINS_CAD = {
    "rudder_joint": np.array([-1.282, -0.0090126, 1.08]),
    "wingsail_joint": np.array([-0.18951, -0.11, -1.522]),
    # Relative to the wingsail link, not the hull.
    "trim_tab_joint_rel_wingsail": np.array([-1.3637, 0.14258, -0.42606]),
}

_HERE = os.path.dirname(os.path.abspath(__file__))
MESH_DIR = os.path.join(_HERE, "..", "models", "polaris", "meshes")


def read_stl(path: str) -> np.ndarray:
    """Reads a binary STL into an (n, 3, 3) array of triangle vertices."""
    with open(path, "rb") as handle:
        handle.seek(80)
        count = struct.unpack("<I", handle.read(4))[0]
        raw = np.frombuffer(handle.read(count * 50), dtype=np.uint8).reshape(count, 50)
    return raw[:, 12:48].copy().view("<f4").reshape(count, 3, 3).astype(np.float64)


def write_stl(path: str, tris: np.ndarray) -> None:
    """Writes an (n, 3, 3) triangle array as a binary STL, recomputing facet normals."""
    count = len(tris)
    normals = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0])
    lengths = np.linalg.norm(normals, axis=1, keepdims=True)
    normals = np.divide(normals, lengths, out=np.zeros_like(normals), where=lengths > 0)

    record = np.zeros((count, 50), dtype=np.uint8)
    record[:, 0:12] = normals.astype("<f4").view(np.uint8).reshape(count, 12)
    record[:, 12:48] = tris.astype("<f4").view(np.uint8).reshape(count, 36)
    with open(path, "wb") as handle:
        header = b"polaris mesh, generated by tools/prepare_polaris_meshes.py"
        handle.write(header.ljust(80, b"\0"))
        handle.write(struct.pack("<I", count))
        handle.write(record.tobytes())


def weld(tris: np.ndarray, decimals: int = 5):
    """Converts an STL triangle soup into an indexed mesh.

    STL stores every triangle independently, so coincident corners are duplicated and
    the mesh has no edge connectivity. Edge-collapse decimation needs that
    connectivity, so vertices are merged by rounded position first.
    """
    points = tris.reshape(-1, 3)
    unique, inverse = np.unique(np.round(points, decimals), axis=0, return_inverse=True)
    faces = inverse.reshape(-1, 3).astype(np.int32)
    # Welding collapses slivers into degenerate faces; drop them.
    keep = (
        (faces[:, 0] != faces[:, 1])
        & (faces[:, 1] != faces[:, 2])
        & (faces[:, 0] != faces[:, 2])
    )
    return unique.astype(np.float32), faces[keep]


def main() -> int:
    raw_dir = os.path.join(MESH_DIR, "raw")
    if not os.path.isdir(raw_dir):
        print(f"error: {raw_dir} not found -- put the raw CAD STLs there first", file=sys.stderr)
        return 1

    try:
        import fast_simplification
    except ImportError:
        print("error: pip install fast-simplification", file=sys.stderr)
        return 1

    offset = FLIP @ CG_CAD
    for name, target in TARGETS.items():
        src = os.path.join(raw_dir, f"{name}.STL")
        if not os.path.isfile(src):
            print(f"skip {name}: {src} missing")
            continue
        tris = read_stl(src)
        original = len(tris)

        if target is not None and original > target:
            points, faces = weld(tris)
            reduction = 1.0 - target / len(faces)
            points, faces = fast_simplification.simplify(points, faces, reduction)
            tris = points[faces].astype(np.float64)

        # Rotate into the z-up frame; the hull additionally moves onto the CG.
        tris = tris @ FLIP.T
        if name == "base_hull":
            tris = tris - offset

        dst = os.path.join(MESH_DIR, f"{name}.STL")
        write_stl(dst, tris)
        print(
            f"{name:<15} {original:>8} -> {len(tris):>6} tris"
            f"   {os.path.getsize(src) / 1e6:>6.1f} -> {os.path.getsize(dst) / 1e6:.2f} MB"
        )

    print("\nJoint origins in the CG-centred z-up frame (transcribed into model.sdf):")
    for label in ("rudder_joint", "wingsail_joint"):
        print(f"  {label:<30} {np.round(FLIP @ JOINT_ORIGINS_CAD[label] - offset, 5).tolist()}")
    # Child-of-child: rotation only, since it is expressed relative to an already-placed link.
    rel = FLIP @ JOINT_ORIGINS_CAD["trim_tab_joint_rel_wingsail"]
    print(f"  {'trim_tab_joint (rel. wingsail)':<30} {np.round(rel, 5).tolist()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
