name: Build Release Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the Docker image'
        required: true
        type: string
  pull_request:
    types: [opened, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-24.04-arm64
    timeout-minutes: 240

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Generate CACHEBUST timestamp
        id: meta
        run: echo "timestamp=$(($(date +%s%3N)))" >> $GITHUB_OUTPUT

      - name: Build and push release
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          file: .devcontainer/release/release.Dockerfile
          build-args: CACHEBUST=${{ steps.meta.outputs.timestamp }}
          push: true
          tags: |
            ghcr.io/ubcsailbot/sailbot_workspace/release:${{ inputs.tag }}
            ghcr.io/ubcsailbot/sailbot_workspace/release:latest
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
