name: Build Base and Dev Images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Base and dev image tag'
        required: false
        type: string
        default: 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PATRICK_PAT }}

      - name: Build and push base
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:.devcontainer/base-dev"
          file: base-dev.Dockerfile
          push: true
          tags: ghcr.io/ubcsailbot/sailbot_workspace/base:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: base

      - name: Build and push dev
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:.devcontainer/base-dev"
          file: base-dev.Dockerfile
          push: true
          tags: ghcr.io/ubcsailbot/sailbot_workspace/dev:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
