name: Deployment

on:
  push:
    branches:
      - main
      - deployment
  pull_request:
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout workspace
      uses: actions/checkout@v4
    - name: Update docker image
      uses: appleboy/ssh-action@v1.0.3
      with:
        # host: ${{ secrets.SSH_HOST }}
        host: 64.23.224.81
        # username: ${{ secrets.SSH_USERNAME }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd sailbot_workspace
          docker compose -f .devcontainer/docker-compose.yml -f .devcontainer/docker-compose.website.yml up --force-recreate -d
