name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get branch name
      run: export SECRET=${{ secrets.TEST_SECRET }}

    - name: Get ..
      run: echo $SECRET
