name: PR Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: env test
      env:
        MY_VAL: ${{ secrets.TEST_SECRET }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python
