name: Tests

on:
  push:
    branches:
      - main
      - raye
  pull_request:
  schedule:
    # Every Friday at 1:00am UTC
    - cron: '0 1 * * 5'
  workflow_dispatch:

jobs:
  colcon-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test
        uses: ./.github/actions/test/

  ament-lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [lint_cmake, xmllint, flake8, pep257]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linter
        uses: ./.github/actions/ament-lint/
        env:
          LINTER: ${{ matrix.linter }}

  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run linter
        uses: ./.github/actions/clang-tidy/

  # https://github.com/nosborn/github-action-markdown-cli
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Run linter
      uses: nosborn/github-action-markdown-cli@v3.2.0
      with:
        config_file: .markdownlint.json
        files: .
        dot: true

  # https://github.com/gaurav-nelson/github-action-markdown-link-check
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Run linter
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .markdown-link-check.json
        folder-path: .
