name: Website Build Check

on:
  push:
    branches:
      - main
      - '**'
  pull_request:

jobs:
  build-website:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: src/website

      - name: Build website
        run: npm run build
        working-directory: src/website
